- qemu.mk
> Add GP support in xtest build

- mediatek.mk
Signed-off-by: SY Chiu <sy.chiu@linaro.org>
Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173_EVB)
> Added MediaTek platform

- qemu-check.exp
- qemu.mk
Some patches needed for https://github.com/OP-TEE/optee_os/pull/461.
> Travis check

- common.mk
- fvp.mk
- hikey.mk
> Fix all-clean

- fvp.mk
> Fix fvp compilation with GP tests

- common.mk
- hikey.mk
@jbech-linaro @jforissier I've tested about 10+ consecutive boots without problems so this seems stable at least from a booting point of view I suppose. If you can test (both booting and xtest) on your board that would be helpful as well.
```
Result of testsuite XTEST_TEE_TEST:  
25953 subtests of which 0 failed                                                                                       
59 test cases of which 0 failed                                                                                        
0 test case was skipped                                                                                                
TEE test application done!
```
The first commit also replaces #31.
> hikey: Update build instructions

- hikey.mk
Signed-off-by: Victor Chong victor.chong@linaro.org
Tested-by: Victor Chong <victor.chong@linaro.org> (hikey)
> hikey: make console configurable

- mediatek.mk
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (MT8173 EVB)
> MT8173 EVB support official kernel

- fvp.mk
> FVP on 64bits (core and TA)

- hikey.mk
To make it a bit easier to understand how to do a recovery and how to
flash HiKey, we have added a new make target for recovery which tells
how to configure the jumpers and the initiates the recovery itself. In
addition to this we have changed the "flash" make target so that it
does the same as stated in the instructions on the 96boards "Getting
started" page.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (HiKey)
> HiKey: Add recovery target and instructions

- qemu-check.exp
- qemu.mk
> Remove modprobe optee_armtz in case of generic driver

- juno.mk
- kconfigs/juno.conf
- toolchain.mk
> Add support for Juno

- common.mk
- fvp.mk
> fvp: possibility to choose SU and SK compilation mode

- common.mk
- fvp.mk
- hikey.mk
- juno.mk
- mediatek.mk
- qemu.mk
> Use mix compilation mode on all platforms

- common.mk
> CFG_TEE_CORE_LOG_LEVEL no more fixed anymore

- fvp.mk
> fvp: use release to retrieve .bin files

- common.mk
- fvp.mk
- hikey.mk
- juno.mk
- mediatek.mk
- qemu.mk
> Add driver to filesystem only if built as module.

- fvp.mk
- hikey.mk
- juno.mk
- mediatek.mk
- qemu.mk
Tested-by: Victor Chong <victor.chong@linaro.org> (QEMU with CONFIG_OPTEE=m)
> Fix conditional include of driver module

- hikey_debian.mk
- toolchain.mk
Fixes issues seen here:
https://travis-ci.org/OP-TEE/optee_os/builds/137444600#L195
And the build issue mentioned here:
https://github.com/OP-TEE/optee_os/issues/832
> Misc build fixes

- hikey.mk
Instead of using sudo/mount to build the FAT image, use commands from
the mtools package to copy files into the FAT image.  This eliminates
the requirement to use sudo during the build.  It also removes a small
sleep necessary to make umount work.
Signed-off-by: David Brown <david.brown@linaro.org>
> hikey: Use mtools to avoid sudo during build

- hikey.mk
> hikey: recovery does not need sudo if udev is configured correctly

- .gitignore
- qemu_v8.mk
QEMU and OP-TEE on ARMv8 is working
Signed-off-by: Matt Ma <matt.ma@linaro.org>
> qemu_v8: add First build script for QEMU ARMv8-A

- hikey.mk
Tested-by: Victor Chong <victor.chong@linaro.org> (hikey)
> hikey: fix bug: @echo: command not found

- common.mk
- fvp.mk
- hikey.mk
- hikey_debian.mk
- juno.mk
- mediatek.mk
- qemu.mk
- qemu_v8.mk
- rpi3.mk
factorize also all rootfs generation between fvp/juno/qemus/mediatek
> factorize rootfs filelist and image generation

- rpi3.mk
Fix parallel build issue (make -jn), now it works fine
Minor: add additional command for the proper cleanup of rpi3_firmware
target.
> RPi3 parallel build fix

- docs/rpi3.md
Update RPi3 NFS/TFTP steps (current steps are out-dated and don't work)
Minor update of Upstream section
> doc: Update RPi3 NFS/TFTP setup steps

- rpi3.mk
> rpi3: update firmware to newer version

- docs/rpi3.md
Add minor fixes of broken url links
> docs: rpi3: minor: fix url links

- README.md
> docs: Add automake to prerequisites

- README.md
- docs/dra7xx.md
Signed-off-by: Andrew F. Davis <afd@ti.com>
> Add dra7xx.md

- README.md
> docs: Add libssl-dev to prerequisites

- common.mk
- init.d.optee
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)
> rootfs: start tee-supplicant on boot

- qemu-check.exp
Update expect script with new name of test the test cases.
Note sure how to test this without merging it
> qemu-check: test cases renamed to regression_*

- README.md
> docs: Add an image showing current Travis build status

- docs/hikey.md
- hikey_debian.mk
Also add notes to try 'make recovery' if 'make flash' fails
> hikey_debian: Update rootfs to 16.06

- faq.md
Make the faq.md a bit more up to date:
- Update links
- Update Table of Contents
- Refer to Security Advisories page
- Mention Travis OP-TEE build.git job
> doc: update faq.md

- .travis.yml
- qemu_v8.mk
This fixes the build issue for v8 and also makes use of the actual PR/push commit/changes in build.git when running Travis.
> Travis and QEMU v8 fixes

- README.md
- am57xx.mk
- ti/fitImage-am57xx.its
Also related minor PRs:
https://github.com/linaro-swg/gen_rootfs/pull/22
https://github.com/OP-TEE/optee_os/pull/1494
https://github.com/OP-TEE/manifest/pull/51/files
> am57xx: initial support for TI AM57xx

- README.md
> docs: add links to device specific documentation

- README.md
- fvp.mk
- juno.mk
- mediatek.mk
- qemu.mk
- qemu_v8.mk
- rpi3.mk
Replaces https://github.com/OP-TEE/build/pull/147
> Misc minor updates

- common.mk
- docs/hikey.md
- hikey_debian.mk
Depends on https://github.com/OP-TEE/manifest/pull/55
> hikey_debian: Update build for 2.5.0 release candidate

- rpi3.mk
> benchmark: enable benchmark for rpi3

- .travis.yml
> travis: Enable hikey960

- hikey960.mk
> hikey960: Add missing symbolic link

- common.mk
Label phony targets as such
Remove $(EDK2_PATH)/Conf/.cache in edk2-clean-common
Update description for LINUX_CLEANER_COMMON_FLAGS
> common.mk: misc updates

- hikey960.mk
- rpi3.mk
Based on build results https://travis-ci.org/OP-TEE/build/builds/271755688
> build: fix rpi3 and hikey960 builds

- rpi3.mk
Helps to avoid cases with broken rpi3 firmware archive, which happens
when build process was interrupted or because of network issues.
Relates: https://github.com/OP-TEE/manifest/pull/75
```
Reported-by: Bjorn Wennberg <bjorn.wennberg@forgerock.com>
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
```
> rpi3: use firmware fetched by repo

- qemu.mk
Bios loads OP-TEE image v2 binaries instead of the v1 format.
Depends on https://github.com/linaro-swg/bios_qemu_tz_arm/pull/13
> qemu: bios load OP-TEE image v2

- faq.md
> faq: Add entry for calling op-tee from android .apk apps

- hikey.mk
- hikey960.mk
- qemu_v8.mk
> Fix strace dependency

- docs/debug.md
Add Debugging TA section to docs/debug.md
> Update debug readme

- toolchain.mk
> toolchain.mk: download packages over HTTPS

- docs/rpi3.md
> rpi3.md: Link to latest Linaro Debian rootfs

- hikey.mk
- hikey960.mk
- hikey_debian.mk
> hikey*: support migration to BL2_EL3 on arm-tf

- fvp.mk
> fvp: build using buildroot

- hikey.mk
> hikey: build using buildroot

- hikey960.mk
Depends on https://github.com/OP-TEE/manifest/pull/108
This has only been test compiled, not run on hardware.
@jforissier, would you mind giving it a try?
> hikey960: build using buildroot

- juno.mk
> juno: build using buildroot

- kconfigs/u-boot_qemu_virt_v7.conf
- qemu.mk
> qemu.mk: replace bios with u-boot

- poplar.mk
> poplar: fix dead rootfs URL

- common.mk
- docs/qemu.md
> qeu: buildroot: always enable networking

- poplar.mk
> poplar: use buildroot for creating initial rootfs

- qemu.mk
- qemu_v8.mk
Following https://github.com/OP-TEE/build/pull/252 and https://github.com/OP-TEE/build/pull/254, this P-R synchronises the script layout of **qemu.mk** and **qemu_v8.mk**.
Commit comment:
```
Qemu and qemu_v8 are almost built the same way. Main differences are
32b/64b modes and bios_qemu_tz_arm/edk2 as non-secure boot stage.
optee-client targets are removed since now built from the buildroot
target.
This change allows enables SMP testing on qemu_v8 through the QEMU_SMP
directive.
````
> qemu/qemu_v8: synchronise build scripts

- .gitignore
- br-ext/package/optee_client/S30optee
- br-ext/package/optee_client/optee_client.mk
- docs/rpi3.md
- rpi3.mk
- rpi3/firmware/uboot.env.txt
Some general fixes and one of them:
Fixes: https://github.com/OP-TEE/optee_os/issues/2773
> Rpi3 nfs fixes

- qemu_v8.mk
> qemu_v8: Add support for Secure Boot (TBB)

- common.mk
To set additional BR2_ variables, the user currently needs to edit
common.mk and modify the buildroot recipe. It is iconvenient, especially
since a line with a cumbersome syntax has to be added. One would expect
to be able to specifiy the desired value on the make command line or
directly in the Makefile. For instance, to enable debug mode:
make BR2_ENABLE_DEBUG=y.
This patch updates the buildroot recipe to enumerate all the Makefile
variables that start with BR2_, and each such variable is automatically
added to ../out-br/extra.conf.
As a result the existing BR2_ variables can be set in a simpler way.
Tested on QEMU, results in the same ../out-br/.config except for the
line order.
Suggested-by: Heino Madsen <heino.madsen@huawei.com>
> common.mk: buildroot: append BR2_ variables to config automatically

- synquacer.mk
* add SCP build recipe for DeveloperBox
* add required arm-none-eabi toolchain using [GNU Embedded Toolchain for Arm 9-2019-q4][arm-toolchain]
Its manifest is updated in OP-TEE/manifest#151. 
Note that the build is working now because of too large FIP package. The FIP package contains only TF-A and OP-TEE. SCP is not included in FIP, so it is not the cause breaking the build. 
[arm-toolchain]: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
> devbox: build scp

- README.md
Fix outdated links.
Fixes: #414
> doc: update links to the documentation

- common.mk
- qemu_v8.mk
> Qemu v8 32bits

- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157A-DK1.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-DK2.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-EV1.cfg
- stm32mp1.mk
> stm32mp1: fix partitioning description and clean make target

- br-ext/package/optee_os_ext/optee_os_ext.mk
Install all TAs found in devkit into target filesystem.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
> br-ext: install OP-TEE devkit TAs

- common.mk
- poplar.mk
- ti/ti-common.mk
- verdin.mk
Remove unused stuff in makefiles.
> Unused targets

- qemu-check.exp
> qemu-check.exp updates

- get_clang.sh
- toolchain.mk
> toolchain: update to Clang 12 (take two)

- common.mk
- kconfigs/u-boot_qemu_v8.conf
- qemu_v8.mk
> Add options to add in UBOOT

- br-ext/board/qemu/overlay/bin/domu
Please ignore @ruchi393's commits which are in #493, and consider only "qemu_v8: xen: add domu helper script".
> qemu_v8: xen: add domu helper script

- .github/issue_template.md
- .github/pull_request_template.md
Update broken URLs in the issue and PR templates.
> github: update links in issue/PR templates

- juno.mk
TF-A v2.4 and earlier is used with the SCP binaries provided in the
vexpress-firmware git. With TF-A v2.5 is supposed to use the SCP
binaries released at [1] instead. So update to download the SCP binaries
from [1] instead.
Link [1]: https://downloads.trustedfirmware.org/tf-a/css_scp_2.8.0/juno
> juno: download scp version 2.8

- toolchain.mk
> Improve toolchain download and unpack script.

- common.mk
- qemu.mk
- qemu_v8.mk
- soc_term.py
Rewriting `soc_term` in Python, as an alternative to #512.
> Rewrite soc_term in Python

- qemu_v8.mk
A patch to check that Xen and Xen tools have compatible version numbers, plus a minor cleanup.
> Xen tools version check

- qemu_v8.mk
Invoke optee_rust/ci/qemu-check.exp in target "check-rust" to
trigger CI test for Rust applications.
Run check progress:
$ make CFG_TEE_CORE_LOG_LEVEL=0 check-rust
Signed-off-by: Yuan Zhuang <zhuangyuan04@baidu.com>
> qemu_v8.mk: Add CI test for Rust applications

- qemu-check.exp
- trusted-keys.exp
See discussion in https://github.com/OP-TEE/optee_os/pull/5085.
> CI fixes (Trusted Keys with Xen)

- qemu-check.exp
- qemu_v8.mk
XEN fails to boot linux when cpu is selected as max with following
kernel crash. Hence revert to using cortex-a57 when XEN_BOOT is
selected.
[    0.000000] ------------[ cut here ]------------
[    0.000000] kernel BUG at arch/arm64/kernel/traps.c:498!
[    0.000000] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
[    0.000000] Modules linked in:
[    0.000000] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 5.16.0-gdbeb6ea978fc #1
[    0.000000] Hardware name: linux,dummy-virt (DT)
[    0.000000] pstate: 000000c5 (nzcv daIF -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[    0.000000] pc : do_undefinstr+0x2bc/0x2e0
[    0.000000] lr : do_undefinstr+0x2c8/0x2e0
[    0.000000] sp : ffffd399cddc3c60
[    0.000000] x29: ffffd399cddc3c60 x28: ffffd399cddd34c0 x27: 0000000000000000
[    0.000000] x26: …
> qemu-v8: Use cpu as cortex-a57 for XEN_BOOT

- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157A-DK1.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-DK2.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-ED1.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-EV1.cfg
- br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-STM32MP157A-DK1/boot/extlinux/extlinux.conf
- br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-STM32MP157C-DK2/boot/extlinux/extlinux.conf
- br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-STM32MP157C-ED1/boot/extlinux/extlinux.conf
- br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-STM32MP157C-EV1/boot/extlinux/extlinux.conf
- stm32mp1.mk
> stm32mp1: use FIP image format in TF-A and provision a partition for U-Boot env

- qemu-check.exp
- qemu_v8.mk
Introduces the option MEMTAG which enabled tagging of memory using the
ARM Memory Tagging Extension (MTE).
> qemu_v8: Introducing MEMTAG option

- rockpi4.mk
Compute the sizes and offsets required when creating the boot image from BR2_TARGET_ROOTFS_EXT2_SIZE instead of assuming it is fixed to 112M. This allows enabling more Buildroot packages that would not fit into the default image size.
> rockpi4: allow changing root FS size

- versal.mk
Enable sshd.
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
> Versal ACAP: enable network and ssh

- fvp-psa-sp.mk
- fvp/bl2_sp_list.dtsi
- fvp/mm_communicate_carveout.dtsi
- fvp/spmc_manifest.dts
- trusted-services.mk
> FVP TS fixes

- qemu_v8/optee_sp_manifest.dts
> Notification with hafnium

- fvp-psa-sp.mk
- fvp.mk
- fvp/bl2_sp_list.dtsi
- fvp/spmc_manifest.dts
This change adds the Trusted Services logging SP on the FVP platform
> fvp: ts: deploy the logging SP

- kconfigs/u-boot_qemu_virt_v7.conf
Depends on https://github.com/OP-TEE/manifest/pull/285
> QEMU U-Boot version update

- common.mk
Whether it is gnome-terminal, konsole or xterm, they all have key limitations, i,e, they require desktop enviroment, which make it not convenient to develop and test through ssh connection.
Some terminal multiplexers like tmux, screen are more generic and they are supposed to be supported.
This patch add tmux support for `run-only` target.
> qemu: add tmux support.

- common.mk
> Update error message in common.mk

- fvp.mk
Set PATH to include the directory with the clang toolchain when building Hafnium.
> fvp: add path to clang for hafnium build

- qemu.mk
- qemu_v8.mk
> Qemu 9.2.0 fixes

- qemu_v8.mk
Add a $(OUT_PATH) recipe since $(HAFNIUM_BIN) depends on it.
> qemu_v8: add $(OUT_PATH) recipe

- qemu_v8/optee_sp_manifest.dts
- qemu_v8/sp_layout.json
> Hafnium FF-A 1.2

- LICENSE
Import LICENSE file from optee_os repository.
Closes: https://github.com/OP-TEE/build/issues/822
> LICENSE: Add LICENSE file

- qemu_v8.mk
Add a hafnium-clean target and add it to the clean: dependencies so that Hafnium can be cleaned and its submodules re-sync'ed.
> qemu_v8: add hafnium-clean target

- qemu_v8.mk
- qemu_v8/optee_sp_manifest.dts
- qemu_v8/spmc_el2_manifest.dts
> Spmc at el2 updates
