OP-TEE/build

qemu.mk

qemu: suppress spurious 'make' output when printing kernel version

---

qemu.mk

qemu: fix $(ROOT) when current path contains 'build' not at the end

---

common.mk
fvp.mk
hikey.mk
mediatek.mk
qemu.mk

The code added by commits d6536da64deb ("Commonlize xtest compilation
among all platforms") and 070d95595e1d1 ("common build: optee
components") introduces race conditions that break parallel build (make
-jX). This is due to manually launching a make sub-process to run the
-common targets, and can be fixed by just declaring a dependency
instead. Specific flags are appended to common flags, rather than
passed as arguments to a new "make" sub-process.
So, basically:
foo-common:
$(MAKE) -C foo_dir [A=a B=B]
foo:
$(MAKE) foo-common [C=c]
is turned into:
FOO_COMMON_FLAGS ?= A=a B=b
foo-common:
$(MAKE) -C foo_dir $(FOO_COMMON_FLAGS)
FOO_COMMON_FLAGS += C=c
foo: foo-common
At the same time this allows foo: to override flags, for instance
set A=aa in the above example (prior to this, A=a would …

Rework common.mk

---

common.mk
fvp.mk
hikey.mk
mediatek.mk
qemu.mk

Following are made common:
* EDK2
* Busybox
* Linux
Note that on FVP and Mediatek, Linux is now compiled with `AARCH64_CROSS_COMPILE` instead of `AARCH64_NONE_CROSS_COMPILE`

More common part

---

hikey.mk

Adds two new targets, one that downloads the necessary nvme.img file and
another target that flash the device. We have also added a couple of
.PHONY directives to a few targets.

Hikey: Add flash and nvme targets

---

qemu.mk

- Make sure launch-terminal cannot block by adding a '&'
- Use xterm instead of gnome-terminal because it is more likely to be
installed by default.
Fixes https://github.com/OP-TEE/build/issues/18.

qemu.mk: use xterm instead of gnome-terminal

---

qemu.mk

At the moment we start several terminals, and then sleep for a second
before running a QEMU instance which will connect to processes run
in those terminals. This will fail if the terminals are displayed on
a slow remote X11 connection, because the terminals won't have
completed startup before the one second delay elapses.
Replace the delay with a loop that checks whether there's anything
listening on the relevant TCP ports yet.
Fixes #20 (GitHub issue)
Signed-off-by: Peter Maydell <peter.maydell@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
Tested-by: Joakim Bech <joakim.bech@linaro.org>

qemu.mk: Wait for terminals to be started before running QEMU

---

hikey.mk

Fix bug reported in https://github.com/OP-TEE/optee_os/issues/542

Fix incorrect path to simple.script

---

hikey.mk

Sometimes it happens that the umount fails saying that a device/resource
is busy when trying umount the device after the filesystem has been
created. We don't know how and why this happens, but in the meantime
while waiting for a proper solution we have added a sleep that seems to
solve the problem.

hikey: Add sleep to prevent umount failure

---

qemu.mk

GCC 5 and above fails to build OP-TEE project under QEMU.
Warnings are now treated as errors by default.
On line 60 --extra-cflags="-Wno-error" fixes the issue.
Please reference
[OP-TEE/optee_os#50](https://github.com/OP-TEE/optee_os/issues/550) for
specifics.
My machine is running gcc version 5.2.1 20151010 and I can confirm this
now works with change. It affects both default.xml and default_stable.xml repo
configurations for OP-TEE.

qemu: Add "-Wno-error" flag to qemu target

---

kconfig_preempt.conf
qemu.mk

This will hopefully fix occasional errors observed during OP-TEE Travis
regression testing (make check):
rcu_sched detected stalls on CPUs/tasks...

qemu: enable kernel CONFIG_PREEMPT

---

kconfig_no_jffs2.conf
qemu.mk

We have observed random failures of "make check" when run in the
Travis environment (OP-TEE regression testing). Every time it fails,
the log file has the following errors [1]:
Starting QEMU...send: spawn id exp7 not open
while executing
"send -- "\r""
(file "qemu-check.exp" line 54)
== /home/travis/optee_repo/build/serial0.log:
spawn ../qemu/arm-softmmu/qemu-system-arm -nographic [...]
Using QEMU provided DTB at 0x40000000
[...]
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2. (NAND) send: spawn id exp7 not open
while executing
"send -- "\r""
(file "qemu-check.exp" line 54)
== end of /home/travis/optee_repo/build/serial0.log
It seems that QEMU exits unexpectedly as the kernel is initializing
the JFFS2 filesystem driver. Since this is something we don't need, I …

qemu: disable kernel CONFIG_JFFS2_FS

---

common.mk
fvp.mk
hikey.mk
kconfig_no_jffs2.conf
kconfig_preempt.conf
kconfigs/fvp.conf
kconfigs/hikey.conf
kconfigs/mediatek.conf
kconfigs/qemu.conf
mediatek.mk
qemu.mk

- Kernel config fragments that were used by the QEMU makefile are
merged into kconfigs/qemu.conf. Now, each platform has its own file
in kconfigs/
- All platforms: CONFIG_DMA_SHARED_BUFFER cannot be enabled directly
because it is  a not a visible symbol (has no prompt in Kconfig).
CONFIG_DRM is set instead which depends on DMA.
- kconfigs/hikey.conf: keep only what is necessary

Use common rule for linux/.config and per-platform config fragments

---

fvp.mk
qemu.mk

Update with new TA dev kit name for FVP and QEMU.
Depends on https://github.com/OP-TEE/optee_os/pull/566

FVP QEMU: Update with new TA dev kit name

---

common.mk
hikey.mk
mediatek.mk

common: Add CROSS_COMPILE_ta_arm## flags
hikey and mediatek: Update with new TA dev kit name

Add support for 64-bit TAs

---

fvp.mk

Update build arguments for ARM-TF.
Note: depends on updating to the rebased OP-TEE patches at
https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_armtf_v1.2

FVP: update ARM-TF

---

qemu-check.exp

Fixes 'make check' error introduced by commit 6f0c0eb95ea8 ("qemu: Add
'-machine secure=on' to arguments).

qemu-check.exp: remove duplicate 'virt' keyword

---

common.mk

OPTEE_LINUXDRIVER_CLEAN_COMMON_FLAGS needs to specify the module M
flag, else linux is cleaned instead of optee_linuxdriver.

common: Fix optee_linuxdriver clean target

---

kconfigs/qemu.conf

The line disabling CONFIG_JFFS2_FS was removed by mistake by commit
a6d968c8bc63 ("qemu: generic driver"). Restore it to fix the Travis
tests.

kconfigs/qemu.conf: restore '# CONFIG_JFFS2_FS is disabled'

---

fvp.mk
hikey.mk
juno.mk
mediatek.mk
qemu.mk
toolchain.mk

- Adds legacy toolchain for use in older edk2 projects, this is the only
project using the pre 5.x toolchain for now
- Removes the bare metal toolchain
- qemu: Change the path for libraries for GCC5
- fvp: compiler changes for ARM-TF and EDK2
Update libteec path in initramfs
- mtk: Toolchain and libteec path updates
- juno: Toolchain and libteec path updates
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU, FVP, HiKey)

gcc5: Update to use gcc5

---

common.mk
fvp.mk
hikey.mk
hikey_debian.mk
juno.mk
mediatek.mk
qemu.mk
qemu_v8.mk

Many users are still using https://github.com/jenswi-linaro/lcu14_optee_hello_world as a reference to start writing TAs, probably because diving directly into xtest requires some effort, but since lcu14_optee_hello_world is not maintained, it can make supporting these users difficult, so add to our build system a maintained version of hello_world TA, i.e. https://github.com/linaro-swg/hello_world.
Tested-by: Victor Chong <victor.chong@linaro.org> (qemu)

Add support for hello_world TA

---

qemu_v8.mk

Replaces broken edk2 link with a slightly older but working link.

qemu_v8: replace broken edk2 link

---

mediatek.mk

When we started using GCC5.x the path for libraries was changed. The
same change is needed for MTK8173 also.

mtk8173: Change path to libteec.so

---

qemu-check.exp

When "make check" is run and an assertion fails in TEE core, secure
world hangs, and therefore xtest hangs too. "make check" will not
report the failure and exit until a timeout occurs (480s).
In order to detect the error condition sooner, open the TEE core log
file and add a trigger on "assertion ... failed at ...".

qemu-check.exp: monitor TEE core log file and detect assertion failures

---

toolchain.mk

Change path to relative to current dir, the same as in common.mk

Fix toolchain.mk ROOT path

---

toolchain.mk

Fixes https://github.com/OP-TEE/optee_os/issues/1195.

toolchain.mk: Update legacy toolchain download url

---

common.mk

With the recently fixed UUID changes (commit in optee_os:
(9a8a19cdba48dbca89c2a35d7984e9ec28f97bda) we missed to fix the hello
world TA.
Depends on https://github.com/linaro-swg/hello_world/pull/6

Fix incorrect UUID for hello world TA

---

toolchain.mk

Update toolchain urls to 5.3-2016.05, which has support of ARMv8.1 arch
features, enabled by default on some setups with linux kernel v4.9 (rpi3)
ARMv8.1 architectural features in linux kernel:
CONFIG_ARM64_HW_AFDBM
CONFIG_ARM64_PAN
CONFIG_ARM64_LSE_ATOMICS
CONFIG_ARM64_VHE
With the previous toolchain I was receiving such compilation issues:
`Error: selected processor does not support 'staddlh w0,[x1]'`

toolchain: update toolchain to support ARMv8.1

---

rpi3/firmware/uboot.env.txt

Add runtime kernel comandline creation (for both mmc/nfs boot)
The same as described in http://wiki.dave.eu/index.php/Change_Linux_Command_Line_Parameter_from_U-boot
Minor: reordered vars (just grouped it a bit)
Type (default Boot sequence) `run mmcboot` to load `Image`/`optee.bin`/dtb file/mount rootfs from MMC
Type `run nfsboot` to download `Image`/`optee.bin`/dtb file from TFTP server/mount rootfs over NFS
BTW, I'll also add patches to documentation/rpi3.md tomorrow 
```
Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (rpi3)
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
```

U-Boot env bootargs cleanup

---

hikey.mk

It seems like there where some leftovers from the consolidation of the
filesystem generation patches a while ago. This cleans up duplicates
etc and fixes an error when generating the root fs due to recent
changes.

hikey: Use common rules for TAs etc

---

docs/debug.md
docs/fvp.md
docs/hikey.md
docs/juno.md
docs/mtk8173.md
docs/qemu.md

Use a relative path to README.md instead of a URL, so that the file for
the current HEAD is shown.

docs: fix broken links to README.md

---

hikey_debian.mk

- Use a newer boot image (pre-built 16.06 UEFI image)
- Remove sudo requirement when using burn-boot
- Add udev rules help, similar to the hikey.mk file
- Step up OPTEE_PKG_VERSION to 2.3-0
Known issues:
- On HiKey 4G devices it seems like the partition table is to small to
be able fit the newer 16.06 Debian root fs. It might be that we can
tweak the partition table a bit, but for the moment we will keep using
the 16.03 Debian root fs.
- When running this on the device
$ dpkg --force-all -i /tmp/linux-image-*.deb
there will be errors like this:
blockdev: ioctl error on BLKROSET: Operation not permitted
According to the comments in:
https://github.com/OP-TEE/optee_os/issues/1234
that message only shows up on the 16.03 root fs and it seems to only
show up when running later kernel versions. …

hikey: Update HiKey Debian for 2.3.0 release

---

rpi3/firmware/uboot.env.txt

U-boot dhcp/bootp client changes "serverip" variable value in case if it was specified in a dhcp/bootp server configuration. 
Renamed `serverip` var, which now is used for `nfsboot` target to avoid updating of this value by DHCP/BOOTP clients and just to use our pre-defined static value.

Fix for serverip issue

---

.travis.yml
toolchain.mk

In the quest for updating to GCC6.x I wanted to investigate the ability to automate building full OP-TEE repo configurations (only build, no testing). After lots of trail and error and reading I think I've manged to come up with something that works pretty good using Travis. An example of a complete and successful build looks like this (and some of you will probably get an email when Travis has completed the build for this PR):
https://travis-ci.org/jbech-linaro/build/builds/195839345
Individual build time for each project is ~40 minutes and in total it runs for 1h 20min. I have played with enabling caches, but I don't think I've got it working as it should. Because 40 minutes is quite much time compared to local (cached) setups on my own computer. Unfortunately it's a guessing game, …

Travis enablement

---

faq.md
toolchain.mk

This is the patch that step up default toolchain in build.git to GCC6.x. Note that I had to add a dummy patch for Travis so that it was actually checking out GCC6.x when running the Travis job. That should not be included when merging this. I'll remove that when adding R-B tags etc. However, my push looked good on my local branch, see -> https://travis-ci.org/jbech-linaro/build/builds/199189080                                                   
So, hopefully this should be it.

Final piece of the toolchain upgrade (gcc6.x)

---

faq.md

On https://www.op-tee.org/faq/ after 9, 10 comes. This is due to a know github bug. If we can add a line break, I assume this should fix the rendering issue on the website.

Fix for the website render

---

qemu-check.exp

Since commit 1333db4d959b ("rootfs: start tee-supplicant on boot"),
there is no need to start tee-supplicant from qemu-check.exp.

qemu-check.exp: do not start tee-supplicant

---

qemu_v8.mk

Change link from build 716 to latest to prevent it from becoming outdated.

qemu_v8: Update broken link

---

fvp.mk

Adds switch --arm-v8.0 to FVP command line to enable ARM v8.0
architecture only.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)

fvp: emulate ARM-v8.0

---

README.md

Device tree compiler is also needed for U-Boot compilation for TI platforms

doc: minor: add dtc to prerequisites

---

docs/ti.md
ti/ti-common.mk
ti/uEnv.txt

uEnv.txt was needed due to a bug in the default U-Boot environment,
this has been fixed upstream and the TI repo used in this build.
Remove this file.
Signed-off-by: Andrew F. Davis <afd@ti.com>

ti: Remove uEnv.txt for TI builds

---

.travis.yml

Regardless if it is a push or a pull request, Travis will use the
committers repository and branch. For developers this means his own
branch will be used when pushing to his own gits and when making a pull
request. When the pull request is merged, which is seen as normal push
to the upstream repository, Travis will once more build according to the
definition, but this time use the upstream repository and the tip branch
instead.

travis: Always use the branch from the committer

---

.travis.yml

It seems like Travis have changed the images in such a way that there is
already a $HOME/bin folder, therefore we must use the '-p', when
creating the folder in our .travis.xml file.

Travis: Add -p when create the bin folder

---

qemu_v8.mk

Enable support of benchmark framework on QEMUv8
See also https://github.com/OP-TEE/manifest/pull/61
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>

qemu_v8: enable benchmark support

---

common.mk

Related to https://github.com/linaro-swg/optee_benchmark/pull/2
`optee_benchmark` was previously using both `CROSS_COMPILE` and `HOST_CROSS_COMPILE` in its Makefile, causing build errors.

common.mk: use CROSS_COMPILE for optee_benchmark

---

common.mk

When LAUNCH_TERMINAL is not set, `make run` hangs with the following
messages:
soc_term: save_current_termios: tcgetattr: Inappropriate ioctl for device
soc_term: save_current_termios: tcgetattr: Inappropriate ioctl for device
The reason is an invalid test in common.mk.
Fixes: 07580605eabd ("common.mk: allow user to override launch-terminal in make run")

common.mk: fix invalid empty test on $(LAUNCH_TERMINAL)

---

docs/rpi3.md
rpi3.mk
rpi3/firmware/config.txt

1. Add Bus Bluster config/usage details
2. The Raspberry Pi 3 allows to enable JTAG on the GPIO via the
enable_jtag_gpio=1 flag in the config.txt, which is more prefarable.
Switch to this method
3. Add physical memory map
4. Change information about usage of Sequitur labs OpenOCD fork to
the uptsteam OpenOCD, as it already has ARMv8 support
Relates: https://github.com/linaro-swg/u-boot/pull/2
Deprecates: https://github.com/OP-TEE/build/pull/164
https://github.com/OP-TEE/build/pull/155
```
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org>
Suggested-by: Joseph Pantoga <jp@redballoonsecurity.com>
```

rpi3: update jtag debugging details

---

common.mk
fvp.mk
hikey.mk
hikey_debian.mk
juno.mk
mediatek.mk
qemu.mk
qemu_v8.mk
rpi3.mk
ti/ti-common.mk

New `optee_examples` git rep is used instead of `hello_world`, which will contain different sample applications that will show usage of specific TEE functionality (crypto examples, random data generation, trusted storage etc.)
Filelist of examples for rootfs is generated inside `optee_examples` `Makefile`
Currently, `example` targets are only defined inside `qemu.mk`
Relates to: https://github.com/linaro-swg/optee_examples/pull/1

examples: use optee_examples instead of hello_world

---

common.mk

Typo s/example/file/.
Review indentation.

common: fix install of optee-examples TAs

---

hikey_debian.mk

Commit 584efe5b ("examples: use optee_examples rep") missed this spot.

hikey_debian: Fix bug copying ta to deb package

---

hikey_debian.mk

Commit 584efe5 ("examples: use optee_examples rep") copies CAs to a wrong
location.

hikey_debian: Copy CAs to the proper location

---

common.mk
hikey.mk
hikey960.mk
hikey_debian.mk
rpi3.mk

I'll create another PR in `optee_benchmark`, where libyaml is used for emitting timestamps data into the file (more convient for further parsing by python app + more user-friendly)
Relates to: https://github.com/linaro-swg/optee_benchmark/pull/3/

Move MULTIARCH def to common.mk/libyaml support

---

qemu-check.exp
qemu.mk

Commit 37ab51d ("qemu: bios load OP-TEE image v2") has updated the run
and run-only targets, but not make check. Fix this.

qemu: fix "make check" to use OP-TEE image v2

---

hikey.mk
hikey960.mk

Adds missing atf-fb dependency to lloader.

hikey: add missing atf-fb dependency

---

hikey_debian.mk

hikey_debian: add missing arm-tf and atf-fb dependencies to l-loader

---

qemu-check.exp

Now that OP-TEE supports several cores in QEMU, use 4 of them when
running "make check". This is hopefully more likely to catch any
concurrency bug.

qemu: use 4 virtual CPUs (-smp 4) for "make check"

---

fvp.mk

The path to the executable in FVP Foundation model has changed, update
the path accordingly.

fvp: update path to simulator executable

---

qemu_v8.mk

ERROR_DEPRECATED=1 may cause build errors when ARM deprecates APIs
upstream. Since we're tracking upstream master, it can happen at any
time, and indeed we have just met this build issue:
plat/qemu/qemu_bl31_setup.c:129:2: error: unknown field 'g0_interrupt_num' specified in initializer
.g0_interrupt_num = ARRAY_SIZE(irq_sec_array),
^
Although we usually want to use the latest APIs, having a build that
can break randomly is not nice to our users. Therefore, remove the
ERROR_DEPRECATED flag from our Makefile to fix the compile error and
give us some time to adapt to upstream changes.
Of course, the weakness in this reasoning is that by removing
ERROR_DEPRECATED, we are likely to not even notice when an API has
changed. Anyway, this seems to be the most reasonable option given that
there is …

qemu_v8.mk: remove ARM-TF flag: ERROR_DEPRECATED=1

---

common.mk
fvp.mk
fvp/grub/grub.cfg

This will move away from the old EDK2 landing team release and instead use latest and greatest from the official EDK2 tree(s). With this we are using a proper boot-image instead of relying on semihosting (which isn't supported in EDK2 anymore, which has only been on the Linaro landing-team branches).
To try this out one needs the commits in https://github.com/OP-TEE/manifest/pull/84. I.e., both this PR and the one in manifest.git needs to be merged at the same time.
If one want to try this on a local forest (just to show that this **can** be done with repo also, although I personally prefer [checking out the PR's from GitHub directly](https://help.github.com/articles/checking-out-pull-requests-locally/) instead, since that is just a oneliner), then one can:
```bash
$ repo init -u …
```

FVP: Use official EDK2 and use boot image instead of semihosting

---

common.mk
fvp.mk
qemu_v8.mk

With the introduction of edk2-platforms ([manifest/PR85](https://github.com/OP-TEE/manifest/pull/85)) we need to update the default edk2-platforms path to the built firmware.

qemu v8: Use default path from edk2-platforms

---

docs/debug.md

This is the updates needed here due to the trace changes in https://github.com/OP-TEE/optee_os/pull/2011.

docs: update debug.md to match the new trace output

---

hikey.mk
hikey960.mk
qemu_v8.mk

Travis seems to [be happy with this fix](https://travis-ci.org/jbech-linaro/build/builds/329375926) and this resolves the [build issue](https://travis-ci.org/OP-TEE/build/builds/329285971) showing up on the daily build last night.
Multiple personality support in strace is not something that we make use
of in OP-TEE for the moment, so instead of putting more prerequisites on
our builds let us just disable this feature in strace.

strace: Disable multiple personality support

---

common.mk

Fix benchmark build regression, which was introduced by output path changes in
optee_benchmark last patches.

benchmark: fix paths for libyaml/benchmark app

---

.travis.yml

With the recent QEMU v7 changes in manifest.git:
918f04199c ("qemu: general cleanup and remote changes")
where the remote "github" was introduced, we introduced a regression for
the QEMU v7 Travis builds. The remote name "github" has been used in
Travis when setting up a remote for the build.git itself. By renaming
the remote we do not get any naming collisions and the Travis build
script will be prepared for similar changes in manifest.git for the
other platforms.

travis: rename the github remote

---

qemu_v8.mk

Like other platforms (fvp.mk, hikey.mk, hikey960.mk, hikey_debian.mk)
define the edk2-call macro to invoke the EDK2 build script rather than
$(MAKE) directly. Indeed, the edk2-clean-common target in common.mk
expects $(edk2-call) to take the 'cleanall' argument, which the EDK2
build script does accept, but the EDK2 makefile doesn't (there is no
cleanall rule in EDK2).
Fixes:
$ make clean
[...]
make[1]: Entering directory '/home/jerome/optee_repo_qemu_v8/edk2'
make[1]: *** No rule to make target 'cleanall'.  Stop.
Another option to fix the above error would be to change the edk2-clean
target to no use edk2-clean-common and call "$(MAKE) clean" directly.
But then, it would be inconsistent with other platforms and the EDK2
build script may be a better interface than raw make (more stable). …

qemu_v8.mk: update edk2-call to invoke the EDK2 build script

---

qemu_v8.mk

The 'strace-clean' target runs the 'clean' target in the strace project
directly, and afterwards removes the Makefile and configure scripts as well.
This is the same strategy used by other platforms using strace (hikey.mk and
hikey960.mk), however other platforms check for the existence of the Makefile
before executing $(MAKE), allowing a build to be cleaned multiple times.
Without this check, subsequent invocations of 'strace-clean' (or simply
'clean') fail as there is no Makefile to use.
Fixes:
$ make strace-clean
[...]
$ make strace-clean
[...]
make[1]: Entering directory '/home/goatshriek/optee-armv8/strace'
make[1]: *** No rule to make target 'clean'.  Stop.
Signed-off-by: Joel Anderson <jeander@vt.edu>

qemu_v8.mk: update strace-clean to test for Makefile

---

qemu-check.exp

Since commit eed314d11475 ("qemu: build using buildroot"), the login
and the shell prompts of the root FS have changed. Adjust our "make
check" accordingly.

qemu-check.exp: fix expected prompts

---

README.md

The format and the name of the OP-TEE maintainers file has changed.
Update references accordingly.

README.md: fix link to OP-TEE maintainers file

---

.travis.yml

MTK8173 in manifest.git has just recently been deprecated and therefore
we need to remove it from Travis.

travis: remove MTK8173 build

---

juno.mk

BL0 has been renamed to SCP_BL1.
Bl30 has been renamed to SCP_Bl2.
Update makefile accordingly

juno: scp binaries renamed

---

hikey960.mk

Commit f9f39124efd1 ("hikey*: support migration to BL2_EL3 on arm-tf")
has updated the flash target to use hisi-nvme.img instead of nvme.img,
thus adopting the new naming introduced by upstream commit b5ae2c13438e
("installer: add hisi- prefix to ptable, sec_xloader, fastboot,
sec_uce_boot, and sec_usb_xloader imgs").
Unfortunately, the line dealing with sec_xloader.img was not updated.
Do it to fix "make flash".

hikey960.mk: fix name of hisi-sec_xloader.img

---

qemu.mk

This build arm-trusted-firmware for qemu cortex-a15.
bios_qemu_tz_arm is still used as the primary non-secure boot stage.
Depends on https://github.com/OP-TEE/manifest/pull/110.

qemu_virt: boot from arm-tf and allow smp test

---

README.md

Checking Qemu arguments expects the tool 'expect'.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

qemu/qemu_v8: dependecy for make targets 'check'

---

qemu.mk

Now that Arm Trusted Firmware is used as the secure boot loader
and bios_qemu_tz_arm is used as the non-secure bootloader, all binaries
are expected to be found in the $(BINARIES) directory. Symbolic links
are created by various targets in the qemu.mk.
The 'check' target should create a link to rootfs.cpio.gz, similar to
the 'run' target.
Fixes: 46ddff2b339b9 ("qemu: boot from arm-tf")

qemu: make check: create symlink to rootfs.cpio.gz

---

am43xx.mk
am57xx.mk
common.mk
dra7xx.mk
ti/ti-common.mk

Changes for the TI platforms to use buildroot instead. I'm not able to test this myself. @igoropaniuk, @glneo, can you help?
To build this:
```
repo init -u https://github.com/jenswi-linaro/manifest.git -m dra7xx.xml -b remaining-br
cd build
git remote add jenswi https://github.com/jenswi-linaro/build.git
git fetch jenswi
git checkout jenswi/remaining-br
```
then build and flash as usual.

am32xx am57xx dra7xx: build using buildroot

---

qemu_v8.mk

As for qemu.mk, environment can set the number of cores to be emulated
using QEMU_SMP. Defaults to 1 core.
This change is relates to https://github.com/OP-TEE/optee_os/pull/2339 and eases testing qemu_v8 over more cores.

qemu_v8: ease SMP testing through QEMU_SMP

---

docs/rpi3.md
rpi3.mk

Depends on https://github.com/OP-TEE/manifest/pull/116.
```bash
U-Boot 2016.03-00725-gbc6d93cf5e (Jun 11 2018 - 21:07:15 +0200)
...
I/TC:  OP-TEE version: 3.1.0-141-ga0a7d92c #1 Mon Jun 11 19:07:19 UTC 2018 aarch64
...
[    0.000000] Linux version 4.6.3-01139-g7d976fc52ae3 (jbech@debby) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11) ) #1 SMP Mon Jun 11 21:16:51 CEST 2018
...
buildroot login: root
...
+-----------------------------------------------------
16055 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!

Rpi3: build using Buildroot

---

fvp.mk
hikey.mk
hikey960.mk
hikey_debian.mk

Grub 2.02 has a harmless warning with recent GCC compilers. Avoid the
problem by configuring Grub with --disable-werror.

grub: ignore harmless warning

---

hikey960.mk

The files used by "make recovery" have been renamed [1].
Link: [1] https://github.com/96boards-hikey/tools-images-hikey960/commit/b5ae2c13438e

hikey960: update name of recovery files (hisi-*)

---

docs/qemu.md

Now that buildroot is used, the 'mount_shared' alias is not available
anymore. Document the full command instead.

qemu: doc: fix host folder sharing documentation

---

br-ext/board/qemu/overlay/etc/init.d/S50udhcpc
common.mk

Adds the missing startup file to the buildroot-generated filesystem so
that networking is available in the VM as claimed by docs/qemu.md.

qemu: buildroot: fix networking

---

br-ext/package/optee_client/S30optee
br-ext/package/optee_client/optee_client.mk

Note: first commit is https://github.com/OP-TEE/build/pull/290.
Updates so that `tee-supplicant` and `xtest` may be run as a non-root user.

buildroot: run tee-supplicant as non-root

---

br-ext/configs/optee_generic
br-ext/package/optee_client/S30optee
br-ext/package/optee_client/optee_client.mk

Restrict execution of TEE client applications to members of the teeclnt
group. A test user is created and added to this group.
Having two groups (tee and teeclnt) allows to better isolate
tee-supplicant from the client applications.

buildroot: add teeclnt group and test user account

---

br-ext/package/optee_client/S30optee
br-ext/package/optee_client/optee_client.mk

If /dev/ion exists, it should be set up so that the test user can access
it. Otherwise, some tests will fail, such as xtest 1014 (Secure Data
Path). Similar to what is done for /dev/tee*, this commit configures
permissions based on a specific group: ion.

buildroot: optee_client: add ion group and set permissions on /dev/ion

---

fvp.mk
fvp/grub/grub.cfg

The Device Tree configuration we need for the Foundation Platform is now
available upstream (v4.18) as foundation-v8-gicv3-psci.dts (it only lacks
the optee node and memory reservations). Let's use this new file instead
of a hacked version of foundation-v8.dts modified for PSCI and GiCv3.

fvp: use DT file foundation-v8-gicv3-psci.dtb

---

common.mk
qemu.mk
qemu_v8.mk

common.mk mistakenly uses the QEMU overlay (which currently contains
only an init script for udhcpc) on all platforms. This is incorrect and
causes problems on RPi3 at least [1].
Fixes: commit 751b35bb0b84 ("qemu: buildroot: fix networking")
Links: [1] https://github.com/OP-TEE/optee_os/issues/2478#issuecomment-432818199

buildroot: use QEMU overlay only when platform is QEMU or QEMUv8

---

qemu.mk
qemu_v8.mk

Use two vCPUs by default instead of one. This configuration is more
likely to trigger race conditions when testing.

qemu, qemu_v8: set QEMU_SMP ?= 2

---

fvp.mk

Adds support for Arm Trusted Firmware-A version v2.0.
TF-A v2.0 does not acccept FVP_USE_GIC_DRIVER=FVP_GICV3_LEGACY anymore.
Therefore, use FVP_GICV3 instead. This is the default value with v2.0, and
is also supported by earlier versions (such as 1.5 which is the one we are
using currently).
OP-TEE is configured accordingly (CFG_ARM_GICV3=y).
~~** Note ** Depends on an optee_os patch, see PR 2548.~~ That was PR 2560, merged.

fvp: use GICv3 to support TF-A v2.0

---

common.mk
rpi3.mk

Spawn getty for both HDMI and serial console. Leverage
post-build.sh script for rpi3, which adds getty line for
tty1 in inittab [1].
[1]: https://patchwork.ozlabs.org/patch/602668/

rpi3: spawn getty for both HDMI and serial console

---

rpi3/debugger/pi3.cfg

While doing updates to [the upcoming optee_docs / RPi3](https://optee.readthedocs.io/building/devices/rpi3.html#jtag), I've tested JTAG at the same time and found out that there was indeed an issue with the pi3.cfg file. I found another config that makes it working again and now it seems like having all 4 cores enabled also behaves nicely.
Fixes an old issue also (already closed): https://github.com/OP-TEE/build/issues/257

rpi3: update OpenOCD configuration for RPi3

---

br-ext/package/optee_client/S30optee

Update script based on the feedback from Buildroot maintainer [1]:
>  > \+# /etc/init.d/optee
> 
>  Drop this comment, it is useless, and in fact wrong: the file will not
>  have this name in a Buildroot filesystem.
>
> (...)
> > \+	if [ -e /usr/sbin/tee-supplicant -a -e /dev/teepriv0 ]; then
>
> Drop this test, just start tee-supplicatn.
> (...)
> > \+		echo "Starting tee-supplicant..."
> > \+		/usr/sbin/tee-supplicant &
>
> Please use start-stop-daemon. See
> https://patchwork.ozlabs.org/patch/994013/ for the "right" way of
> writing an init script.
This maybe not be best way, if there's one, but it seems more
standard to use start-stop-daemon. Moreover the proposed script
ensures its return value matches the status of the caller request.
Note that I preserved the **status** case which …

[RFC] optee services: update script

---

br-ext/Config.in
br-ext/package/optee_os/CMakeLists.txt
br-ext/package/optee_os/Config.in
br-ext/package/optee_os/optee_os.mk
common.mk

When OP-TEE is built with CFG_ULIBS_SHARED=y, TA shared libraries are
created. They have to be installed into the target root FS in order
to be found at runtime.
This patch adds a custom package to do just that.

buildroot: add optee_os package to copy shared libraries into the root FS

---

zynqmp.mk
zynqmp/arm-trusted-firmware/arm-trusted-firmware_2018.2.bb
zynqmp/kernel_optee.cfg
zynqmp/linux-xlnx_%.bbappend
zynqmp/optee-client/optee-client.bb
zynqmp/optee-os/optee-os.bb
zynqmp/optee-test/optee-test.bb
zynqmp/system-user.dtsi

This commit adds support for Xilinx ZynqMP boards to the OPTEE/build repository.
The provided makefile relies on Xilinx Petalinux 2018.2 itself based on Yocto.
Petalinux and BSP files shall be downloaded from Xilinx website. You may have to create a Xilinx account.
The makefile helps to create, patch and build a customized Petalinux project with OP-TEE support.
Boards can be emulated using Petalinux's QEMU.
xtest test suite pass on Petalinux's QEMU emulating zcu102 board executing Petalinux v2018.2 and OP-TEE 3.4.0

Add support for Xilinx zcu102, zcu104 and zcu106 ZynqMP boards

---

hikey.mk

Provide an additional option for CFG_NW_CONSOLE_UART and CFG_SW_CONSOLE_UART
to use the secondary console on the 40-pin Low Speed Connector, namely UART2.
Signed-off-by: Michalis Pappas <mpappas@fastmail.fm>

hikey: Add support for UART2

---

br-ext/package/optee_os/optee_os.mk

Fixes a mistake in the optee_os install step which prevents the
libraries from being copied into the root FS staging area.
Fixes: 91ebff727d47 ("buildroot: add optee_os package to copy shared libraries into the root FS")

buildroot: fix installation of shared libraries

---

common.mk

On recent versions of gnome-terminal you will get this warning:
"Option "-t" is deprecated and might be removed in a later version of
gnome-terminal."
There seems to be no substitution for it, therefore let's just get rid
of it.

common: remove depraceted gnome-terminal flag

---

synquacer.mk

This commit add supports to build flash binaries for DeveloperBox.
It builds an OPTEE binary, a FIP package containing the OPTEE,
a flash image containing the FIP package and EDK2, and its
corresponding update capsule.
This does not build edk2-non-osi's fip_all_arm_tf_mm.bin yet.
Signed-off-by: Pipat Methavanitpong <pipat.methavanitpong@linaro.org>

Add support for DeveloperBox

---

rpi3.mk

Make use of the PLATFORM variable to set the specific
target being used "rpi3-b" or "rpi3-bplus".
Signed-off-by: Philby John <philby.j@hcl.com>
Signed-off-by: Vv Ramya <ramyavv@hcl.com>

Add support for Raspberry Pi 3 B plus

---

hikey.mk
hikey960.mk

STRACE_PATH is a leftover from before buildroot and is not used anymore
so remove it.

hikey, hikey960: remove unused variable STRACE_PATH

---

rpi3.mk

In commit (7fbd6ce22a) "common.mk: buildroot: append BR2_ variables to
config automatically", flags were refactored and the old
BUILDROOT_GETTY_PORT got replaced with BR2_TARGET_GENERIC_GETTY_PORT.
Because of that Rpi3 didn't spawn a console when booting up. By setting
BR2_TARGET_GENERIC_GETTY_PORT to ttyS0 things will work again.
@glneo , I believe the `dra7xx am57xx am43xx` also suffer from this. If you can confirm, then I can add patches for them too in this PR.

rpi3: set BR2_TARGET_GENERIC_GETTY_PORT

---

am43xx.mk
am57xx.mk
dra7xx.mk

In commit (7fbd6ce22a) "common.mk: buildroot: append BR2_ variables to
config automatically", flags were refactored and the old
BUILDROOT_GETTY_PORT got replaced with BR2_TARGET_GENERIC_GETTY_PORT.
TI platforms (am43xx, am57xx and dra7xx) were'nt updated hence the wrong
ttyAMA0 were used instead of ttyS0 (am43xx and dra7xx) and ttyS2
(am57xx). By setting BR2_TARGET_GENERIC_GETTY_PORT properly, this issue
gets resolved.

ti platforms: set BR2_TARGET_GENERIC_GETTY_PORT

---

poplar.mk

Provide TF-A path for l-loader
`Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>`

poplar: provide TF-A path for l-loader

---

br-ext/package/optee_examples/optee_examples.mk
br-ext/package/optee_test/optee_test.mk

The PR consists of 2 commits for easier review, as the issue might also affect the build of examples.
The first commit fixes https://github.com/OP-TEE/build/issues/389, the second commit adapts the fix for examples.
If desired, both commits can be merged when adding the Reviewed-By-line to the commit message or the second commit can be split of into its own PR.

Fix #389: OP-TEE test build statement overflowing execvp

---

zynqmp.mk
zynqmp/optee-os/optee-os.bb
zynqmp/rootfs_config

This PR adds support for Ultra96 board.
It relies on ultra96 flavor added to OP-TEE ZynqMP platform.
zynqmp makefile is modified in the following way:
- Default BSP rootfs is replaced by a minimal rootfs which supports
zcu10x and Ultra96 boards.
- New petalinux-package target available to generate BOOT.BIN file.

zynqmp.mk: Add support for Ultra96 ZynqMP board

---

qemu-check.exp
qemu_v8.mk

Updates qemu_v8.mk and qemu-check.exp so that "make check" and "make
check-only" are supported for QEMUv8, as they are for QEMU.

qemu_v8: fix "make check"

---

qemu.mk
qemu_v8.mk

The QEMU and QEMUv8 builds do not need any kernel module to boot and
run xtest etc. so we can save build time by only building the kernel
image by default.

qemu, qemu_v8: do not build Linux modules

---

qemu_v8.mk

The kernel image for QEMUv8 is Image, not zImage (there is no
compressed image support in Linux for arm64). Fix the makefile.
Fixes: c54f4f51fafb ("qemu, qemu_v8: do not build Linux modules")

qemu_v8: fix linux build

---

hikey960.mk

The current EDK2 code fails to build with GCC 9.x:
make[3]: Entering directory '/home/jerome/work/optee_repo_hikey960/edk2/BaseTools/Source/C/GenVtf'
gcc  -c -MD -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-deprecated-declarations -Wno-unused-result -nostdlib -c -g  -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/  -O2 GenVtf.c -o GenVtf.o
In file included from /usr/include/string.h:494,
from ../Common/FvLib.h:21,
from GenVtf.c:19:
In function ‘strncpy’,
inlined from ‘ConvertVersionInfo’ at GenVtf.c:132:7:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation] …

hikey960: fix EDK2 build with GCC 9.x

---

common.mk
hikey.mk
hikey960.mk

Fix EDK2 build error when host compiler is GCC 9.x. This is the same fix
as the one recently applied to hikey960.mk.

hikey: fix EDK2 build with GCC 9.x

---

hikey.mk

We currently do not copy any kernel module into our root FS, they are
not needed. Therefore, drop the "modules" target when building the
kernel to save compile time.

hikey: do not build kernel modules

---

.github/issue_template.md
.github/pull_request_template.md
.github/workflows/stale_issue.yml

The GitHub templates and actions are useful to the "build" git also,
therefore recursively sync up (copy) the .github folder from optee_os.
Note, that here we have also done some changes to the GitHub actions. In
optee_os we have two different actions files, one for issues and one for
pull requests. It seems like it is possible to combine them into a
single action file as shown in the actions examples [1]. Another change
is that we also exclude marking issues stale if they already have the
label "bug". Note that we're only excluding issues, since PR's should
not have the "bug" label to start with.
Link: [1] https://github.com/actions/stale/blob/master/README.md
P.S. The checkpatch "maintainers" warning is there which we'll ignore. But no …

GitHub: sync GitHub templates and actions from optee_os

---

zynqmp.mk
zynqmp/optee-os/optee-os.bb
zynqmp/optee-test/optee-test.bb
zynqmp/python/python-pycryptodome.inc
zynqmp/python/python-pycryptodomex.inc
zynqmp/python/python-pyelftools.inc
zynqmp/python/python3-pycryptodome_3.9.3.bb
zynqmp/python/python3-pycryptodomex_3.9.3.bb
zynqmp/python/python3-pyelftools_0.25.bb

Currently one has to patch the PetaLinux installation to add these
missing dependencies. However, there should be no need to touch the
installation, which is often not feasible in e.g. corporate environments
anyway. Different OP-TEE releases require different dependencies; this
patch has been tested for all releases down to 3.4.0.
See OP-TEE/optee_docs#54 for the corresponding documentation pull request.

zynqmp: add missing Python package build dependencies

---

br-ext/package/optee_examples/optee_examples.mk
br-ext/package/optee_test/optee_test.mk

If an error occurs when building a TA, the error does not stop the
build. It may therefore go unnoticed if files have been generated
previously.
This patch updates the buildroot hooks that deals with TAs and breaks
the loop as soon as a TA faiils to build. A non-zero status is left to
the caller (a Buildroot makefile) and the build stops as expected.

br-ext: break build as soon as one TA fails to build

---

verdin.mk

Add initial verdin.mk for the minimal setup for OP-TEE testing.
This setup uses latest mainline TF-A (v.2.2) / U-Boot (v2020.03) /
Linux (5.6-rc).
Verdin i.MX8M Mini boot sequence:
```
BootROM -> SPL -> TF-A (BL31) -> OP-TEE (BL32)
|
-> U-Boot (BL33) -> Linux
```
TF-A(bl31.bin), U-Boot proper and OP-TEE (tee.bin) are packed in FIT image,
which is parsed by SPL.
Deploying:
1. Flasing flash.bin (IMX ready-to-boot image):
```
> dhcp && tftpboot ${loadaddr} flash.bin
> setexpr blkcnt ${filesize} + 0x1ff
> setexpr blkcnt ${blkcnt} / 0x200
> mmc dev 0 1 && mmc write ${loadaddr} 0x2 ${blkcnt}
```
2. Boot Linux kernel via TFTP/NFS:
```
-> setenv serverip <ip_of_your_server>
-> setenv nfsroot /path/to/nfs/root
-> setenv fdt_file fsl-imx8mm-verdin-dev.dtb
-> setenv bootargs …
```

verdin-imx8mm: add initial setup

---

get_clang.sh
toolchain.mk

Add "make clang-toolchains" to download and extract Clang 9.0.1 into
$(ROOT)/clang-9.0.1. Usage:
$ make clang-toolchains
$ PATH=../clang-9.0.1/bin:$PATH make COMPILER=clang

toolchain.mk: add clang-toolchains target

---

hikey.mk

Let hisi-idt.py decide which python interpreter is used based on the
hashbang line. Calling "python" can cause compatibility problems when
"python" is Python 2 but the script needs Python3.

hikey: do not call hisi-idt.py with hardcoded python command

---

kconfigs/u-boot_qemu_virt_v7.conf

Update U-Boot config fragment to support more recent U-Boot version than currently used v2018.07 
in Qemu/Armv7 setup.
A later change in OP-TEE manifest repo will dump U-Boot to latest stable version v2020.04 for the Qemu/Armv7 manifest.

qemu: update u-boot config fragment for v2019.01 to v2020.04

---

hikey.mk

The EDK2/UEFI welcome message when booting into fastboot mode has
changed since a while ago [1], but we never updated it correspondingly
in our Makefile, so do it now.
LINK: [1] https://github.com/96boards-hikey/edk2/commit/f5d1102d7bf42ede641520c5c228a0e51139a58e

hikey.mk: update help text for 'make flash'

---

qemu-check.exp

The message displayed by "make check" when an assertion failure is
detected is redundant and possibly misleading. For instance:
$ PATH=~/work/clang-10.0.0/bin:$PATH make -j10 COMPILER=clang check
[...]
Starting QEMU... done, guest is booted.
Running: xtest...
'##########!!! TEE core assertion failed: 'assertion 'maps[map_idx].sz == sz' failed at ldelf/ta_elf.c:1351 in ta_elf_print_mappings()
make: *** [Makefile:221: check] Error 1
$
The "TEE core assertion failed:' part is not needed and possibly
misleading in this case (the assertion occured in ldelf which is
arguably not "TEE core"). Remove it.

qemu-check.exp: clean assertion failure message

---

fvp.mk

The path to the simulator when unpacked has changed in recent FVP
foundation model. Adjusting the path to match the latest version
11.11_34.

fvp: update path to simulator

---

br-ext/package/optee_test_ext/optee_test_ext.mk

The optee_test TAs are built by a $(wildcard ...) loop. This is
unreliable because there is no guarantee that os_test_lib and
os_test_lib_dl will appear before os_test in the list. Yet os_test
depends on the libraries being built first.
Fix the issue by explicitely listing the libraries and TAs with
dependencies in the correct order, then using a wildcard for the other
TAs.

optee_test_ext.mk: make sure TAs are built in correct order

---

rpi3.mk

(This doesn't matter whether it's merged right away of after the 3.12.0 release)
In some cases depending on configurations etc 32MB is a bit tight for
the boot partition. By increasing it to 64MB you are in a better
position for not hitting the limit. Likewise you can store additional
kernel versions in the boot partition which can be useful when debugging
issues showing up in one kernel build, but not the other. Because of
this the help text should state 64MB instead of 32MB.

rpi3: recommend 64MB for the boot partition

---

poplar.mk

Default enable CFG_ENABLE_EMBEDDED_TESTS for OP-TEE os for Poplar.
Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>

poplar: default enable CFG_ENABLE_EMBEDDED_TESTS for optee-os

---

qemu_v8.mk

Set PYTHON3_ENABLE=TRUE so that EDK2 is built with Python 3. Python 2 is
deprecated. Requires EDK2 tag edk2-stable201905 or later.

qemu_v8: use Python 3 when building EDK2

---

common.mk

Add the --disable-docs option to QEMU_CONFIGURE_PARAMS_COMMON so that no
documentation is generated during the QEMU build. Documentation is not
needed and it may fail to build in some environments. For instance on
Ubuntu 18.04.5 LTS:
Warning, treated as error:
docs/qemu-option-trace.rst.inc:4:Malformed option description '[enable=]PATTERN', should look like "opt", "-opt args", "--opt args", "/opt args" or "+opt args"
make[1]: *** [.docs_built_system_qemu.1_docs_built_system_qemu-block-drivers.7_docs_built_system_qemu-cpu-models.7.sentinel.] Error 2
The error is caused by sphinx-build:
$ sphinx-build --version
sphinx-build 3.2.1
The version that comes with Ubuntu 20.04.1 LTS works fine:
$ sphinx-build --version
sphinx-build 1.8.5

common.mk: qemu: do not build docs

---

rpi3.mk

Intermingled logs on RPI3B+ https://github.com/OP-TEE/optee_client/issues/234
In this issue I wanted to ssh onto my rpi3 board so that the normal and secure world logs could be separated . During this course of action I realised my rpi3 board was not able to connect to the local network and to resolve it I have done the following.
I have added the below mentioned packages in order to get an IP assigned to the raspberry pi board and also to ssh onto it from the host Ubuntu. 
**Reason :** By default after buillding the image from the cloned the sources of the build.git for raspberrypi-3 (rpi3) board , I tried to ssh onto my board. 
I figured it out that these packages are missing and were needed to get an IP assigned from the dhcp and also ssh server related packages were needed inorder to …

Added Network support and ssh related packages

---

br-ext/board/stmicroelectronics/stm32mp1-tz/genimage-STM32MP157C-EV1.cfg

stm32mp1: Fix 157C-EV1 bootfs partition image name parameter
Genimage script configuration had wrong image name on bootfs partition. changed the parameter "image" to correct name for the image to be generated successfully and to allow successful boot on STM32MP157C-EV1 board.
Signed-off-by: Timothée Cercueil <litchi.pi@protonmail.com>
Signed-off-by: Timothée Cercueil <timothee.cercueil@st.com>
Acked-by: Jerome Forissier <jerome@forissier.org>

Fix STM32MP157C-EV1 image generation

---

qemu.mk
qemu_v8.mk

The qemu target currently runs the configure script unconditionally
which takes some time and causes unnecessary recompilations.
Split the configuration and the build steps and make the configuration
depend on $(QEMU_PATH)/config-host.mak to avoid the above issue.

qemu, qemuv8: avoid needless rebuilds

---

common.mk

'make edk2-clean' fails with the following error:
build.py...
: error 000E: One Path in PACKAGES_PATH doesn't exist
/home/jerome/work/optee_repo_qemu_v8/edk2/../edk2-platforms
The reason is $(ROOT)/edk2-platforms does not exist on this platform.
Fix this by using the proper platform-specific variable
$(EDK2_PLATFORMS_PATH) in the edk2-clean-common target like is done in
edk2-common.

qemu_v8: fix error in edk2-clean

---

qemu.mk
qemu_v8.mk

As discussed in https://github.com/OP-TEE/manifest/issues/179
+ Older EDK2 toolchains (GCC49) will cause errors when updating EDK2, therefore, we use GCC5 instead.
+ QEMU has adopted meson as the build system. As a result, the output of QEMU will be located in the $(QEMU_PATH)/build, so we should reflect this change.

Update the EDK2 toolchain and QEMU invoking commands

---

common.mk

Remove deprecated dependencies on target optee-os-clean-common. The targets where removed by commit 819066fb88a6.
Fixes build failure with trace like:
```bash
bash> make clean -j$(nproc)
(...)
make: *** No rule to make target 'xtest-clean-common', needed by 'optee-os-clean-common'.  Stop.
```

common: remove deprecated dependency for optee-os-clean-common

---

br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-STM32MP157C-ED1/boot/extlinux/extlinux.conf

Fix path of the DTB file for ED1 that wrongly pointed to the EV1 DTB
file path.
Fixes: 4dc6908c60bf ("stm32mp1: define STM32MP15C-ED1")
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

stm32mp1: fix DTB path in STM32MP15C-ED1 extlinux file

---

imx.mk
imx/u-boot_boot_script

Hello,
Here is a pull request as discussed in [issue 476](https://github.com/OP-TEE/build/issues/476). It enhances the compilation process for the NXP i.MX 8MQuad Evaluation Kit, so the rootfs can be located on a partition and be persisted across boots instead of relying on a RAMDisk. This feature can be enabled using the compilation flag `USE_PERSISTENT_ROOTFS=1`.
I have also refactored the image generation, so the size depends on its content, rather than having a fixed size of 128MiB.
I have run `xtest` with the rootfs located on RAMDisk and a physical partition on an SD card, and both report successful results:
```
25843 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
Feel free to ask for script improvements, I am not …

imx: add a compilation flag to support the persistence of the rootfs.

---

qemu_v8.mk

Commit c993ec995a9e ("qemu_v8.mk: add scripts_gdb kernel build target")
has added "$(MAKE) -C $(LINUX_PATH) $(LINUX_COMMON_FLAGS) scripts_gdb" to the
linux: recipe. Since linux: depends on linux-common which already runs
"$(MAKE) -C $(LINUX_PATH) $(LINUX_COMMON_FLAGS)", and since
$(LINUX_COMMON_FLAGS) contains "Image", the Image target is made twice.
It is more efficient to remove the added line and add scripts_gdb to
LINUX_COMMON_FLAGS instead.

qemu_v8: add scripts_gdb to LINUX_COMMON_FLAGS

---

qemu_v8.mk

The readability check of the host kernel makes sense only when
XEN_BOOT=y, so avoid annoying users that are not concerned by this.

qemu_v8.mk: do not warn about unreadable kernel if XEN_BOOT != y

---

common.mk

Use security_model mapped-xattr for QEMU_PSS_HOST_DIR.
This allows folders/files below /data/tee to be owned by
any uid/gid of the QEMU context.
Fixes https://github.com/OP-TEE/build/issues/478
Signed-off-by: Christoph Gellner <cgellner@de.adit-jv.com>
Suggested-by: Jerome Forissier <jerome@forissier.org>

Use security_model mapped-xattr for QEMU Persistent Secure Storage

---

qemu_v8.mk

make-virt-fs is used to generate xen.ext4 but is passed '-t vfat'
instead of '-t ext4'. Fix that.
In fact 't -vfat' happens to be working in general, presumably because
the actual format of the image is detected at runtime. However, I could
not manage to make a VFAT image work in a Docker container based on
Ubuntu 21.04 and with the following kernel image package installed:
linux-image-kvm/hirsute-updates,now 5.11.0.1009.9 amd64 [installed]
The error messages are as follows:
root@32b61ad4d7f3:~/optee_repo_qemu_v8/build# LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 virt-make-fs -t vfat /root/optee_repo_qemu_v8/build/../out/bin/xen_files /root/optee_repo_qemu_v8/build/../out/bin/xen.ext4
[...]
libguestfs: trace: mount_options "utf8" "/dev/sda" "/"
guestfsd: => mkfs (0x116) took 0.47 secs
guestfsd: …

qemu_v8.mk: xen: pass -t ext4 instead of -t vfat to make-virt-fs

---

qemu_v8.mk

Replaces virt-make-fs with make_ext4fs since its more robust on Ubuntu
and also a bit faster.
Fixes build problems like:
virt-make-fs -t ext4
/home/jens/work/repos/qemu_v8_xen/build/../out/bin/xen_files
/home/jens/work/repos/qemu_v8_xen/build/../out/bin/xen.ext4
Image Name:   Root file system
Created:      Wed Jun 30 19:34:06 2021
Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
Data Size:    31978230 Bytes = 31228.74 KiB = 30.50 MiB
Load Address: 44000000
Entry Point:  44000000
libguestfs: error: tar_in: tar subcommand failed on directory: /: tar:
./rootfs.cpio.gz: Wrote only 6144 of 10240 bytes
tar: Exiting with failure status due to previous errors
make: *** [Makefile:362: xen-create-image] Error 1

qemu_v8: xen: replace virt-make-fs with make_ext4fs

---

qemu.mk

```
qemu-check.exp needs the environment variable $XEN_BOOT to be set,
or the following error is displayed:
$ make check
...
(read trace on "::env(XEN_BOOT)")
invoked from within
"if {$::env(XEN_BOOT) == "y"} {
info " (Xen Dom0)"
}"
(file "/<...>/qemu-check.exp" line 119)
```

qemu: export XEN_BOOT for make check

---

hikey.mk

After trying to use upstream EDK2 on my HiKey board without success,
I reached a point where even 'make recovery' would not make the board
bootable again. The recovery process failed like so:
$ make recovery
[...]
Waiting for device... [35][34][33][32][31][30][29][28][27][26][25][24][23][22][21][20][19][18]
Sending /home/jerome/work/optee_repo_hikey/build/../l-loader/recovery.bin ...
Done
fastboot flash loader /home/jerome/work/optee_repo_hikey/build/../l-loader/l-loader.bin
< waiting for any device >
Sending 'loader' (39 KB)                           FAILED (remote: 'invalid partition')
fastboot: error: Command failed
make: *** [Makefile:351: recovery] Error 1
The solution to this problem is mentioned in [1] and consists in
running 'fastboot getvar partition-size:ptable' before the …

hikey: fix 'invalid partition' error during recovery

---

br-ext/board/qemu/post-build.sh

When VIRTFS_AUTOMOUNT=y and/or PSS_AUTOMOUNT=y, QEMU prints the
following warning:
qemu-system-aarch64: warning: 9p: degraded performance: a reasonable
high msize should be chosen on client/guest side (chosen msize is <=
8192). See https://wiki.qemu.org/Documentation/9psetup#msize for
details.
Let's set the buffer size to 64K mainly to silence this warning. The
performance is noticeably increased too although it doesn't really
matters for typical OP-TEE use cases.

qemu, qemu_v8: set msize when mounting host filesystem

---

common.mk

Current linux config file generation does not add the cross compilation
flags, leading potentially to compilation errors. Not sure how a proper config
file is generated with current implementation but issues are observerd
specially when buildling the linux image with a single thread.
Signed-off-by: Ibai Erkiaga <ibai.erkiaga-elorza@xilinx.com>

linux-defconfig: explicit compile flag usage

---

kconfigs/qemu.conf

Since Linux commit dcb3b06d9c34 ("tee: optee: replace might_sleep with
cond_resched") in v5.11, setting CONFIG_PREEMPT=y in kconfigs/qemu.conf
is not needed anymore. It was a workaround for the missing call to
cond_resched() in the TEE driver. At that time, might_sleep() together
with preemption enabled allowed to get rid of some RCU warning messages
when running long operations in secure world such as large key generation
(test case: "xtest -l 1 4007_rsa"). With cond_resched() the preemption
settings do not matter anymore.
As a result of this change, QEMUv8 is unmodified (CONFIG_PREEMPT=y is
set by default in the kernel's arch/arm64/configs/defconfig), but 32-bit
QEMU now has CONFIG_PREEMPT disabled. Both platforms are tested and
4007_rsa runs as expected with no warning.
Signed-off-by: …

qemu: do not force kernel CONFIG_PREEMPT=y

---

br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk

When upgrading from Buildroot 2021.2 to 2021.08, the following error
occurs:
$ make buildroot
...
GEN     /home/jerome/work/optee_repo_qemu_v8/out-br/Makefile
Your PATH contains spaces, TABs, and/or newline (\n) characters.
This doesn't work. Fix you PATH.
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/jerome/work/optee_repo_qemu_v8/out-br'
make: *** [common.mk:323: buildroot] Error 2
The space comes from the line that appends the toolchain to the PATH in
optee_rust_examples_ext.mk. Fix it.

optee_rust_examples_ext.mk: remove extra space in PATH

---

common.mk

"cargo: command not found" occurs when building Rust examples.
"source ~/.cargo/bin" doesn't work in some environments. Replace
that with adding the PATH.
Signed-off-by: Yuan Zhuang <zhuangyuan04@baidu.com>

common.mk: fix cargo error when building Rust examples

---

.github/workflows/stale_issue.yml

- Update 'stale' from v1.0 to v4.0.1.
- Give 'write' permissions to actions (pull requests and issues).
- Add 'enhancement' to 'exempt-issue-label', so we that stale doesn't
automatically close issues and pr's with the 'enhancement' label.
- Add 'exempt-pr-label' to match exempt-issue-label'.
- Add and set (to true)
remove-issue-stale-when-updated
remove-pr-stale-when-updated
which will automatically remove the 'Stale' label when someone adds a
new comment to a ticket marked as stale.

GitHub actions: General updates

---

.github/workflows/stale_issue.yml

When running the GitHub action, there is a warning:
Unexpected input(s) 'exempt-issue-label', 'exempt-pr-label', valid
inputs are ... 'exempt-issue-labels', 'exempt-pr-labels'.
Add the missing 's' to labels to fix the issue.
This is a new warning after upgrading to the 'Stale' action to v4.1.0,
so they must have changed to the plural version in more recent versions.

GitHub actions: fix runtime warning

---

common.mk
toolchain.mk

Lets switch over to using aarch64 hosted cross-compiler for aarch32
rather than building toochain for aarch32 from source which is very
combersome. But in case of native build for aarch64 on aarch64 host we
are left with no choice but to use buildroot toolchain as Arm doesn't
provide binary toolchain releases for aarch64 native compiler.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>

toolchain: Add optimizations for aarch64 host

---

qemu_v8.mk

-cpu max provides support of maximum feature set available with
AArch64 architecture.This includes FEAT_PAuth and FEAT_BTI.
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

qemu_v8: Use -cpu max to support additional AArch64 features

---

qemu_v8.mk

Introduces option PAUTH, which can be used to enable
Pointer Authentication for TA's.
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

qemu_v8: Introducing PAUTH option

---

qemu_v8.mk
qemu_v8/spmc_el3_manifest.dts

Please wait with this until after the release.
Adds support for building TF-A and OP-TEE the SPMC at EL3.
A special manifest is added to be consumed by the SPMC.
Needed by https://github.com/OP-TEE/optee_os/pull/5141

qemu_v8: add support for EL3 SPMC

---

imx.mk

Adds a missing linux dependency for the flash-image target.
This should fix erros like:
CC [M]  drivers/gpu/drm/nouveau/nvkm/subdev/i2c/bus.o
mformat -i .../build/../out/boot.img.fat -n 64 -h 255 -T 131072 -v "BOOT IMG" -C ::
mcopy -i .../build/../out/boot.img.fat .../build/../linux/arch/arm64/boot/Image ::
.../build/../linux/arch/arm64/boot/Image: No such file or directory

imx: add missing linux dependency for flash-image

---

br-ext/patches/xen/0001-optee-immediately-free-RPC-buffers.patch
common.mk

Adds a patch to be applied by Buildroot when building Xen. This fixes a
race condition in RPC buffer management, which causes random failures in
the OP-TEE CI jobs [1].
Link: [1] https://dev.azure.com/OPTEE/optee_os/_build/results?buildId=2827&view=logs&j=705748f3-7146-5e86-79af-1c0266d20a8c&t=d3458a7d-1a81-5639-8e63-8927d807e53a&l=7812
Fixes: https://github.com/OP-TEE/optee_os/issues/5288

qemu_v8: xen: apply patch to fix issue with RPC buffer release

---

hikey.mk

CFG_FLASH_SIZE can be used to generate only linux-4g or linux-8g instead
of both.

hikey: generate only one of linux-4g and linux-8g

---

qemu_v8.mk

With LOG_LEVEL=50 and DEBUG=1, BL31 becomes too big, with LOG_LEVEL=40
we will miss a few debug prints, but it will at produce a valid binary
and more importantly, you'll get an elf-file with all debug symbols,
i.e., it's GDB makes up for the missing prints.
(FWIW, there is a compiler error with `50` as well, I'll send a fix for that to TF-A)

tf-a/qemu v8: Change LOG_LEVEL to 40 when DEBUG=1

---

br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk
common.mk

Hi,
Teaclave TrustZone SDK 0.2.0 is released and the release note is in https://github.com/apache/incubator-teaclave-trustzone-sdk/releases/tag/v0.2.0.
Besides the release there are some fixes and updates, so `optee-rust` in OP-TEE repo is expected to be pinned to https://github.com/apache/incubator-teaclave-trustzone-sdk/commit/3272b38b013395e3376a38af6315633239d26c1c. I've opened a PR:https://github.com/OP-TEE/manifest/pull/211.
In the new version of Teaclave TrustZone SDK, OPTEE_DIR is checked in setup.sh. If OPTEE_DIR is not set, it will download OP-TEE source code. So set OPTEE_DIR as the directory of OP-TEE repo.
Best Regards,
Yuan

optee-rust: fix building errors

---

br-ext/patches/xen/0001-xen-arm-optee-Fix-arm_smccc_smc-s-a0-for-OPTEE_SMC_D.patch

Adds a Xen bug fix from upstream [1]. With this we will be able to get
rid of a revert in the linux kernel [2].
Link: [1] https://github.com/xen-project/xen/commit/1c3ed9c908732d19660fbe83580674d585464d4c
Link: [2] https://github.com/linaro-swg/linux/commit/665750f493d3fcf307952f19c0442c092b76d852

xen: add upstream patch to fix OPTEE_SMC_DISABLE_SHM_CACHE

---

common.mk

"make optee-rust OPTEE_RUST_ENABLE=y" always runs the setup.sh script
in $(ROOT)/optee_rust. The script clones about 600 MB of data. That
can't be done each time especially since the check-rust target depends
on optee-rust.

optee-rust: prevent new execution after successful build

---

br-ext/patches/xen/0001-optee-enable-OPTEE_SMC_SEC_CAP_MEMREF_NULL-capabilit.patch

Adds Xen upstream patch "optee: enable OPTEE_SMC_SEC_CAP_MEMREF_NULL
capability" in order to avoid failures in the GlobalPlatform test
suite [2]:
optee/build $ export GP_PACKAGE=~/work/TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z
optee/build $ make -j10 XEN_BOOT=y run
...
$ xtest gp_
...
gp_10081 FAILED first error at gp_10000.c:1653
gp_10082 FAILED first error at gp_10000.c:1673
gp_10083 FAILED first error at gp_10000.c:1693
gp_10155 FAILED first error at gp_10000.c:3346
gp_10156 FAILED first error at gp_10000.c:3366
gp_10157 FAILED first error at gp_10000.c:3386
gp_10229 FAILED first error at gp_10000.c:5039
gp_10230 FAILED first error at gp_10000.c:5059
gp_10231 FAILED first error at gp_10000.c:5079
gp_10303 FAILED first error at gp_10000.c:6732
gp_10304 FAILED first …

xen: add patch to support OPTEE_SMC_SEC_CAP_MEMREF_NULL

---

qemu-check.exp

The regular expression used to detect TEE core panics or assertion
failures must not allow multi-line text to match, otherwise the following
input may trigger it:
E/TC:? 0 TA panicked with code 0xbeef
E/LD:  Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0x0e302000 size 0x00e000 flags r-xs (ldelf)
E/LD:  region  2: va 0x00112000 pa 0x0e310000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x00113000 pa 0x0e311000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x00117000 pa 0x0e315000 size 0x001000 flags r--s
E/LD:  region  5: va 0x00118000 pa 0x0e410000 size 0x003000 flags rw-s (stack)
E/LD:  region  6: va 0x00184000 pa 0x00001000 size …

qemu-check.exp: match core assert/panic strings on a single line

---

stm32mp1.mk

Configures U-Boot with stm32mp15_defconfig that was introduced in
U-Boot tag v2021.10 for devices booted with OP-TEE and U-Boot stored
in TF-A FIP container. From U-Boot v2021.10 onward,
stm32mp15_trusted_defconfig is dedicated to boot scheme that do not
use TF-A FIP format.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

stm32mp1: rely on stm32mp15_defconfig

---

qemu_v8/xen/guest.cfg

Increase the size of the guest (DomU) RAM from 128 to 160 MB to fix
an issue with xtest 6018:
* regression_6018 Large object
o regression_6018.1 Storage id: 00000001
writing 0
writing 1
writing 2
writing 3
writing 4
writing 5
regression_6000.c:1895: fs_write(&sess, obj, block, block_size) has an unexpected value: 0xffff3024 = TEE_ERROR_TARGET_DEAD, expected 0x0 = TEEC_SUCCESS
regression_6018.1 FAILED
For some reason, this test passes in CI [1] but not on my laptop
("make XEN_BOOT=y run", login: "root", run /bin/domu, login: "test"
then run "xtest 6018"). tee-supplicant receives error ENOSPC when
trying to write to /data/tee. Since the root FS in the guest is a
ramdisk, increasing the RAM seems to be the appropriate solution.
Link: [1] …

qemu_v8: xen: increase guest RAM from 128 to 160 MB

---

common.mk

The warning on option "-t" is remove in below commit.
https://gitlab.gnome.org/GNOME/gnome-terminal/-/commit/54da2fe919634e2d6a6aab392b36449947b812cd
And it seens work again, so add it back to make the
terminal title understandable.
Below is my test environment:
- Ubuntu 21.10
- GNOME Terminal 3.38.1 using VTE 0.64.2 +BIDI +GNUTLS +ICU +SYSTEMD

common: add -t to set initial title for gnome-terminal

---

toolchain.mk

On an Aarch64 host, "make toolchain" does not use parallel jobs when
building the Aarch64 GCC and the following warning is shown:
$ make -j32 toolchains
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
Therefore, add the '+' sign as recommended. This speeds up the build
quite a bit on a 32-core machine for example.

toolchain.mk: allow parallel build of cross-compiler on Aarch64 hosts

---

common.mk

```
Buildroot parallel build is allowed when BR2_PER_PACKAGE_DIRECTORIES is
'y', see commit e9bff1c86e93 ("common.mk: buildroot: enable top-level
parallel build"). When disabled, Buildroot is not supposed to spawn
several make jobs simultaneously. However for some reason it seems it
can happen, see the IBART failure at [1]. The steps:
>>> optee_client_ext 1.0 Fixing libtool files
and:
>>> pcsc-lite 1.9.4 Fixing libtool files
...seem to be running simultaneously and touching the same path (since
per-package is disabled), which results in:
mv: cannot stat '/home/optee/devel/qemu/out-br/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libpcsclite.la.fixed': No such file or directory
package/pkg-generic.mk:331: recipe for target '/home/optee/devel/qemu/out-br/build/pcsc-lite-1.9.4/.stamp_sta …
```

common.mk: buildroot: force make -j1 in buildroot when not per-package

---

fvp-psa-sp.mk
fvp/bl2_sp_list.dtsi
fvp/spmc_manifest.dts
trusted-services.mk

This commit introduces a new packaging option for Secure Partitions. Instead of embedding the images into the OP-TEE binary, TF-A offers a mechanism to encapsulate an SP image and its manifest into an SP package and add that to the FIP.
https://trustedfirmware-a.readthedocs.io/en/v2.6/components/secure-partition-manager.html#secure-partition-packages
TF-A needs two config options to enable this:
- SP_LAYOUT_FILE: This json file contains the path of the SP images and their corresponding manifests. It's generated by Trusted Services.
- ARM_BL2_SP_LIST_DTS: This dts snippet describes where each SP package should be loaded by BL2.
Depends on:
- https://github.com/OP-TEE/optee_os/pull/5519
- https://review.trustedfirmware.org/q/topic:fip-sp

fvp: add support for Secure Partitions in the FIP

---

common.mk

In some environments it has been noted that the Rust setup fails with a netowrk error [1]. It seems to be an issue with the built-in Git library, a workaround being to tell the Rust setup to use the Git command instead. This commit does exactly that, regardless of the environment.
Note: I chose not to restore the OP-TEE Rust build commands removed by [1] in order to reduce the size of the image ($TOP/optee_rust is 1.8GB after building) and avoid disk space issues in the "make check (QEMUv8)" job which uses this image but doesn't build the Rust tests. The "make check-rust (QEMUv8)" job will do whataver it takes.
Link: [1] https://github.com/jforissier/docker_optee_os_ci/commit/6d7f39aec9436168e5e4ce44c4b6f7791575e313

rust: fix make optee-rust

---

fvp-psa-sp.mk

Move a comment line which accidentally added a whitespace to the end of SP_PACKAGING_METHOD default value.
Fixes: db9b8f09aeeb ("fvp: add support for Secure Partitions in the FIP")

fvp: remove extra whitespace

---

zynqmp.mk
zynqmp/bootImage-zynqmp-ultra96.bif
zynqmp/bootImage-zynqmp-zcu104.bif
zynqmp/bootImage-zynqmp-zcu106.bif
zynqmp/fitImage-zynqmp-ultra96.its
zynqmp/fitImage-zynqmp-zcu102.its
zynqmp/fitImage-zynqmp-zcu104.its
zynqmp/fitImage-zynqmp-zcu106.its
zynqmp/zynqmp-optee.dtso

Add support in the build repository for the previously supported evaluation boards. The pull request includes a patch to the DTS overlay to ensure that kernel does not overwrite either ATF or OP-Tee specially in the ZCU104 and Ultra96 boards where DDR memory is more limited.

Zynqmp new platforms

---

versal/fitImage-versal-vck190.its

Signed-off-by: Nathan Menhorn <nathan.menhorn@amd.com>
When executing the command `$ make -f versal.mk image` when following the instructions in:
https://github.com/OP-TEE/optee_docs/blob/master/building/devices/versal.rst#configuring-and-building-for-vck190 
an error is being encountered when trying to recreate this build using Ubuntu 20.04.5 LTS
`../u-boot/tools/mkimage -f versal/fitImage-versal-vck190.its versal/versal-vck190.ub`
`versal/fitImage-versal-vck190.its:17.20-19.15: Warning (unit_address_vs_reg): /images/kernel/hash@1: node has a unit name, but no reg property`
`versal/fitImage-versal-vck190.its:28.20-30.15: Warning (unit_address_vs_reg): /images/fdt-1/hash@1: node has a unit name, but no reg property`
`versal/fitImage-versal-vck190.its:39.20-41.15: Warning …

versal: remove the @ from fitImage-versal-vck190.its

---

soc_term.py

The serv_conn() function should write the data read from the connection to stdout, not stdin. Although stdin appears to work when soc_term is invoked from a terminal in an interactive session, things get bad when trying to redirect its output:
$ ./soc_term 54320 | tee nsec.log
<... make run etc. ...>
^C
$ file nsec.log
nsec.log: empty

soc_term.py: write to stdout not stdin

---

trusted-keys.exp

The check_keyctl_result() procedure doesn't deal with all error cases properly. For example the following error is not reported:
```
[    7.293607] trusted-key-tee optee-ta-f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c: key shm register failed
add_key: Invalid argument
#
```
To make things simpler, rely on the exit status of the commands sent to the guest. The || shell construct is used to trigger the display of an error message ("FAILED"). To avoid having the message in the command themselves, which would make the parsing more complex, a shell function is introduced ("fail"). Then all the check_keyctl_result() procedure needs to do is wait for the next prompt ("# "), while dealing with errors (the "FAILED" word appearing anywhere), key ID (parsing is unchanged), and timeouts (which I have reduced …

trusted-keys.exp: fix error detection

---

zynqmp.mk

Recent patch in optee_os (c89e397c838f443db2b60ab20aac8565d21a8774) added ZCU104 and ZCU106 platform flavours, therefore there is no need anymore to use zcu102 platform to build optee_os for these boards.
Signed-off-by: Ibai Erkiaga <ibai.erkiaga-elorza@amd.com>

zynqmp: use platform name as OPTEE platform

---

kconfigs/u-boot_rockpi4.conf
rockpi4.mk

Many things need kernel modules to work properly (for example, network access). Add support for this with "make LINUX_MODULES=y". It also takes care of configuring the ethernet port using DHCP.
This setting is off by default because for simple OP-TEE testing and development, it is not required, and we'd rather have a smaller image that builds and boots faster.
The kernel log level is set to 6 (KERN_INFO) instead of the default 7 (KERN_DEBUG) to avoid many messages from drivers which otherwise would disturb the session. They can still be seen with dmesg.

rockpi4: build and install kernel modules when LINUX_MODULES=y

---

br-ext/board/rockpi4/post-build.sh
rockpi4.mk

Enable the OpenSSH server in Buildroot and configure it to allow passwordless login for both the 'test' and 'root' accounts.

rockpi4: add sshd

---

fvp-psa-sp.mk
fvp.mk
fvp/bl2_sp_list.dtsi
fvp/spmc_manifest.dts
trusted-services.mk

This pull request multiple changes which are related to the recent changes around the trusted-services project.
- Setting MEASURED_BOOT=n causes TF-A build to fail as it expects a 0/1 value. The first patch fixes this issue.
- Block storage SP was added.
- The trusted-services deployments have been restructured, so the build repo has to follow the new directory structure and enable selecting different SP configurations.
- After updating TF-A to v2.8 the measured boot feature can be enabled with FIP stored SPs.
- Disable UEFI and SPMC tests by default because they require debugging features enabled.

Alignment with trusted-services changes

---

qemu_v8.mk

The Buildroot update [1] brings a new version of Xen. Fix the makefile accordingly.
Link: [1] https://github.com/OP-TEE/manifest/commit/a4dd5a64d1706e8971f1d5c0ea90a64a1e3f7d4c

qemu_v8: update Xen version

---

qemu-check.exp
qemu.mk
qemu_v8.mk

This commit adds a way to exclude tests when running the xtest suite:
- qemu_check.exp now supports "--xtest-args <args>", which passes <args> to the xtest command,
- The CHECK_ARGS make variable is passed to qemu_check.exp.
For example to run the whole test suite but exclude xtest regression_1031:
$ make check CHECK_ARGS="--xtest-args '-x regression_1031'"

qemu, qemu_v8: pass arguments to qemu_check.exp for example to exclude tests

---

versal/bootImage-versal-vck190.bif

Until Bootgen/PLM supports booting OP-TEE, it is TF-A's responsibility to do it..
The PLM simply loads the raw image into the location agreed with TF-A at build time.
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

Versal ACAP: bootgen image file

---

common.mk

Use the toolchains in OP-TEE repo instead of those in $PATH, to avoid potential inconsistency of toolchains.
Related issue: https://github.com/OP-TEE/build/issues/624
Signed-off-by: Yuan Zhuang <demesne@foxmail.com>

optee_rust: change toolchain path searching priority

---

fvp.mk

Introduce a new variable to allow passing extra arguments to the FVP with environment variable or on the make command line. As an example this allows passing trace related configuration.

fvp: enable passing extra arguments

---

qemu_v8.mk

Without the development package installed in the host, the build system will not include slirp support.
This will cause an error when trying to configure netdev's 'user' during qemu boot.

qemu_v8: qemu: configure slirp

---

fvp-psa-sp.mk

Enable the "HArdware Volatile Entropy Gathering and Expansion" daemon to overcome low-entropy conditions in the FVP. Without this the necessary entropy is gathered very slowly after boot which can cause timeouts for some test cases relying on the getrandom() syscall.

fvp: enable haveged package

---

trusted-services.mk

x-test uses the arm-ffa-user driver to talk to the SPMC test SPs, but the driver build was not triggered when SPMC_TESTS is enabled. This change ensures arm-ffa-uses is built when SPMC_TESTS is set to y.

Fix: SPMC test shall build arm-ffa-user driver

---

fvp-psa-sp.mk
fvp/bl2_sp_list.dtsi
fvp/spmc_manifest.dts
trusted-services.mk

Change the naming scheme of the SP binaries to make sure we can add multiple SPs with the same UUID to the system. Added the possibility to compile all TS SPs with the same FF-A UUID (protocol UUID).
This is need to support [5898](https://github.com/OP-TEE/optee_os/pull/5898)
This is a follow-up on [603](https://github.com/OP-TEE/build/pull/603)

ffa: Allow multiple SPs with same UUID

---

trusted-services.mk

TF-A requires to have the SPs in the same order in the FIP as it is defined in ARM_BL2_SP_LIST_DTS. The sp_layout.json controls the order of SPs in the FIP package. Previously the individual JSON fragments were appended to the sp_layout.json file at the end of the SP build. The final order of SP definitions in the sp_layout.json depended on the SP build order which was non-deterministic because of the parallel make jobs. To resolve this issue the JSON merging step is now done after all SPs have been built. The order will follow the order of build-sp calls in the fvp-psa-sp.mk which matches the order of SPs in ARM_BL2_SP_LIST_DTS.

ts: Generate sp_layout.json after SP builds

---

common.mk

Sets CFG_USER_TA_TARGETS to ta_arm32 or ta_arm64 based on COMPILE_S_USER to match the used TA devkit. This avoids problems with in-tree TAs like pkcs11_ta being compiled for a different TA devkit than what is used by buildroot to populate the rootfs.

common.mk: set CFG_USER_TA_TARGETS

---

rpi3.mk

In one of the final build stages, buildroot will strip [1] binaries by running the following on all binaries under ./out-br/target:
$ aarch64-linux-gnu-strip --remove-section=.comment \
--remove-section=.note
When doing that on kernel8.img (which should be a 1:1 copy of ./linux/arch/arm64/boot/Image), the expected "magic" from the kernel header disappears and so does a few other things as well. In short, the kernel image becomes corrupt. Without the magic, U-boot won't pass execution to Linux and will instead fail with the error message: "Bad Linux ARM64 Image magic!"
To prevent kernel8.img from being stripped, we include it in the BR2_STRIP_EXCLUDE_FILES Makefile parameter.
Why this suddenly started to show, I haven't been able to figure out.
Link: [1] …

rpi3: don't strip kernel8.img

---

common.mk
fvp-psa-sp.mk
fvp/bl2_sp_list.dtsi
fvp/spmc_manifest.dts
toolchain.mk
trusted-services.mk

There are couple issues around TS SPs which this patch intends to fix.
- Aligning selection logic for SPs across fvp-psa-sp.mk, bl2_sp_list.dtsi and spmc_manifest.dts so they all include the same set of SPs for a given configuration.
- Pass DTC_CPPFLAGS to TF-A build because it preprocesses bl2_sp_list.dtsi and spmc_manifest.dts which only works if the necessary defines are forwarded properly.
- Increase SPM test SP memory area because they overlap with the current 64kB setting.
- Make RPC protocol UUID feature backwards compatible

fvp: SP configuration fixes

---

toolchain.mk

"make toolchains" is now failing with the following error:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Although I could download the GCC package [1] just fine with Firefox, the same URL does indeed cause an error when downloaded with curl on my laptop (I am using Ubuntu 22.04.2). The same error happens in the OP-TEE CI loop.
It looks like a required CA certificate ("GlobalSign RSA OV SSL CA 2018") is missing in /etc/ssl/certs/ca-certificates.crt.
Add -k to the curl command to disable certificate …

toolchain.mk: do not check server certificate when downloading

---

rpi3.mk
rpi3/scripts/create-image.sh

At [1] we temporarily fixed the issue with the stripped header from the kernel image. There we also suggested to make a future change making it possible to just simply 'dd' an image to the SD-card.
This change introduces a bash script that generates a rootfs partition and a boot partition. The rootfs partition will contain the root filesystem as created by Buildroot, while the boot partition will contain the firmware files placed in a temporary folder, that will be used to created the boot partition. To create the boot partition, we leverage the 'genimage' tool, hence we enable and build that as host tool in Buildroot.
The change removes the need to manually create, mount partitions and copy files to them. With this, it is sufficient to simply 'dd' the generated image to the SD-card. The …

rpi3: create a bootable image

---

common.mk

Fixes https://github.com/OP-TEE/optee_os/issues/6111
The [fTPM coded by Microsoft](https://github.com/microsoft/ms-tpm-20-ref/tree/main/Samples/ARM32-FirmwareTPM/optee_ta/fTPM) targets 32-bit ARM. Hence, the build requires the 32-bit versions of the libraries it links against. However, at the moment, only the 64-bit versions are generated which makes the build fail.
This PR enables the generation of 32-bit libraries only if the fTPM build is enabled, and disables it otherwise, just as the current behavior.

Fix build of fTPM by enabling build of 32-bit libraries

---

hikey.mk
hikey960.mk

EDK2 fails to build when the cross-compiler is GCC 11.3. The error is as follows:
```
/home/pelops2/hikey960/tee321/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c: In function ‘UsbIoBulkTransfer’: /home/pelops2/hikey960/tee321/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c:259:12: error: ‘UsbHcBulkTransfer’ accessing 80 bytes in a region of size 8 [-Werror=stringop-overflow=]
259 |   Status  = UsbHcBulkTransfer (
|            ^~~~~~~~~~~~~~~~~~~~
260 |               Dev->Bus,
|               ~~~~~~~~~
261 |               Dev->Address,
|               ~~~~~~~~~~~~~
262 |               Endpoint,
|               ~~~~~~~~~
263 |               Dev->Speed,
|               ~~~~~~~~~~~
264 |               EpDesc->Desc.MaxPacketSize,
|               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
265 | …
```

hikey, hikey960: edk2: fix build error with GCC 11.3

---

qemu_v8.mk

The git command used to checkout the submodules in the Hafnium repository is wrong. Fix it.
Fixes: e9290f81f9a4 ("qemu_v8: add support for Hafnium as S-EL2")

qemu_v8: fix build error with SPMC_AT_EL=2

---

toolchain.mk

This PR adds "TARGET_ARCH" variable to download either ARM or RISC-V toolchains.
If "TARGET_ARCH" is specified as "riscv", the RISC-V 64-bit toolchain will be downloaded from riscv-gnu-toolchain\[1] repository and decompressed to `toolchains/riscv64` folder.
\[1]: https://github.com/riscv-collab/riscv-gnu-toolchain/releases

toolchain.mk: add RISC-V toolchain downloaded from official release

---

kconfigs/u-boot_qemu_v8.conf
qemu_v8.mk

~~Please ignore the first commit ("qemu_v8: u-boot: fix load address of kernel and RAM disk") which is submitted as https://github.com/OP-TEE/build/pull/670 and review the second one only ("qemu_v8: remove EDK2").~~ Edit: let's review both commits here.

QEMU_v8: remove EDK2

---

qemu-check.exp
qemu_v8.mk

Address the following warning:
$ make run
[...]
qemu-system-aarch64: -no-acpi: warning: -no-acpi is deprecated, use '-machine acpi=off' instead

qemu_v8: use "-machine acpi=off" instead of "-no-acpi"

---

qemu-check.exp
qemu_v8.mk

Export QEMU_VIRT in the check target and update the expect script to use QEMU_VIRT when adding the "virtualization" to QEMU. This enables the check target with Hafnium, that is, SPMC_AT_EL=2.

qemu_v8: use QEMU_VIRT in check target

---

qemu_v8.mk

"make linux" builds the kernel but is not sufficient to prepare all files for "make run-only". On the other hand, "make run" does a bit too many things to be used comfortably when working on the kernel.
Therefore, add target uImage which generates the kernel image ready to be used by U-Boot. With that, kernel development and testing can be done with the following sequence:
1. make
2. Edit kernel sources
3. make -j$(nproc) uImage
4. make run-only
5. Go to 2 -- repeat as needed

qemu_v8: add uImage target

---

common.mk
qemu_v8.mk
qemu_v8/xen/guest.cfg

Do not build a specific root FS for DomU. Instead, re-use the one that is built for Dom0. While this is certainly not a typical real-world configuration, it helps reduce both build time and disk space which is beneficial in many ways, especially for CI.

qemu_v8: xen: re-use Dom0 root FS for DomU

---

fvp/spmc_manifest.dts

TF-A v2.9 introduced a new mandatory property called "tpm_event_log_max_size" to the "tb_fw_config" DTB under the "tpm_evet_log" node. Add this property to the SPMC manifest file for v2.9 compatibility.
See: https://trustedfirmware-a.readthedocs.io/en/latest/components/measured_boot/event_log.html#dynamic-configuration-for-event-log

fvp, spmc: add missing manifest entry

---

qemu.mk
qemu_v8.mk

Depending on how to you connect to internet, the tcp.localhost might not always work. You can eventually end up with the following error message:
(qemu) qemu-system-aarch64: -serial tcp:localhost:54320: Failed to connect to 'localhost:54320': Connecti on refused
qemu-system-aarch64: -serial tcp:localhost:54320: could not connect serial device to character backend 't cp:localhost:54320'
Therefore it's better to instead use 127.0.0.1 when connecting to the serial consoles.
FYI, this just happened to me when being at the osfc.io conf. I first couldn't figure out why the "make-run" didn't work. Then I tried disable my WiFi connection and things worked as expect. But to avoid this, as said in the commit message, I think it's better to use 127.0.0.1 instead.

make: change from localhost to 127.0.0.1

---

versal/bootImage-versal-vck190.bif
versal/plm-firmware_%.bbappend

Adding in the PetaLinux patch that enables XilNvm and XilPuf, which is required by the Versal OP-TEE port.

Adding in the PetaLinux patch that enables XilNvm and XilPuf

---

stm32mp1.mk

Updates path of the Linux kernel in-tree DT files that have moved to vendor sub-directories since kernel v6.5.
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=724ba6751532055db75992fc6ae21c3e322e94a7

stm32mp1: update Linux DTS files path

---

common.mk
qemu.mk
qemu_v8.mk

Make it possible to set the local ports used for the non-secure (QEMU_NW_PORT) and secure (QEMU_SW_PORT) terminal when running QEMU.
When you need to run multiple QEMU/OP-TEE instances (debugging, multi-user etc.) on the same physical (non-containerized environment) computer, this is useful because you can avoid port collisions (port already in use message) by simply setting non-clashing port numbers when running make and thereby also avoid making changes directly to the makefile.

qemu: make local ports in use configurable

---

qemu_v8.mk

"make buildroot" generates rootfs.cpio.gz but it's not sufficient to prepare all files for "make run-only".
Add a target uRootfs to generate the a rootfs image ready to be used by U-Boot.

qemu_v8: add uRootfs target

---

br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk

aarch64-unknown-linux-gnu target is used to compile TAs in no-std mode, so add corresponding support without breaking support for std mode.
Dependency for https://github.com/apache/incubator-teaclave-trustzone-sdk/pull/114

optee_rust_examples_ext: Add TA target for no-std mode

---

kconfigs/u-boot_qemu_virt_v7.conf

smhload set ramdisk_addr_end to the end address of rootfs, but the kernel expect linux,initrd-end
to be the first address after the initrd.
Update the default bootcmd to meet the requirement.

qemu: Correct initrd-end in u-boot config fragment

---

rust.exp

There is no timeout specified in rust.exp. This makes the tests unreliable, because depending on which tests have been run before, the $timeout global variable may have different values. For example, it is set to 900 by qemu-check.exp (the main file), but may be overriden by trusted-keys.exp to 5 seconds. That's not enough in some cases, causing the following error in optee_os CI:
2024-01-19T11:58:23.5778720Z Running signature_verification-rs...
2024-01-19T11:58:28.3431817Z !!! Timeout: Test failed

qemuv8: rust.exp: set timeout to 10 seconds

---

common.mk
toolchain.mk

Rather than invoking custom setup.sh script provided by OP-TEE Rust SDK, add Rust toolchain installation support as part of toolchain Makefile. This allows to separate OP-TEE specific Rust toolchain installation from default Rust toolchain installation. Now all OP-TEE specific Rust toolchains will be installed under: $(ROOT)/toolchains/rust/.

toolchain.mk: Add support for Rust toolchain for aarch{32/64}

---

qemu_v8.mk

There has been random CI build failures reported while building Rust examples. Most of them seems like conflicts with buildroot provided Rust toolchain. So until those are resolved, disable default Rust examples build for now to get the CI passing successfully.

qemu_v8: Disable Rust examples by default

---

common.mk
hikey.mk
hikey960.mk
qemu.mk
qemu_v8.mk
rockpi4.mk
stm32mp1.mk

Adds a linux-menuconfig-common target to run "make menuconfig" with environment and flags matching the configured linux kernel.

common.mk: add linux-menuconfig-common target

---

common.mk

Adds build target `optee-os-devkit` to get the TA devkit be built and installed. It can be later used as a dependency when building external TAs that need to build linked to OP-TEE as early TAs where building OP-TEE core depends on such TAs being already built. This applies to ftpm hence replace the dependency of `ftpm` make target with a dependency on `optee-os-devkit`.

common: target optee-os-devkit builds the devkit

---

br-ext/package/optee_rust_examples_ext/Config.in
br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk
common.mk
qemu_v8.mk
toolchain.mk

Buildroot provides its own Rust toolchain for various Linux user-space
components. However, that toolchain doesn't support nightly version of
Rust complier which we need for OP-TEE Rust examples for the time being.
Due to two separate Rust toolchains being used for different buildroot
components, there are conflicts [1] [2] observed leading to CI errors.
In order to fix them enable OP-TEE specific Rust toolchain specifically
to build OP-TEE Rust examples rather than enabling it for the entire
buildroot build.
Fixes: [1] https://github.com/OP-TEE/build/issues/727
Fixes: [2] https://github.com/OP-TEE/build/issues/728
@DemesneGH fyi..

optee_rust_examples_ext: Fix Rust toolchain conflicts

---

common.mk
qemu-check.exp
qemu_v8.mk
qemu_v8/qemu-v8-scmi-overlay.dtso

Add a dts file with SCMI server node:
- Connect SCMI server to cpufreq
- Populate power domain
- Populate performance domain
- Populate clock
- Populate sensor
The dts file has been generated with qemu dumpdtb option
Add *-with-scmi commands to boot with the scmi server
- run-with-scmi
- run-only-with-scmi

qemu_v8: add scmi server option

---

rust.exp

A timeout of 10 seconds is enough in most cases, but for some debug configurations where OP-TEE runs very slowly ([1], [2]) the signature_verification-rs test may not complete in time. Therefore increase the timeout to 60 seconds.
[1] `make check CHECK_TESTS=rust \`
`        CFG_FTRACE_SUPPORT=y CFG_SYSCALL_FTRACE=y CFLAGS_ta_arm64=-pg`
[2] `make check CHECK_TESTS=rust \`
`        CFG_CORE_DEBUG_CHECK_STACKS=y CFG_STACK_THREAD_EXTRA=256`

qemuv8: rust.exp: increase timeout to 60 seconds

---

br-ext/package/optee_test_ext/optee_test_ext.mk

Rather than enumerating all the TAs and invoking each Makefile individually (optee_test/ta/<ta_name>/Makefile), user the higher level Makefile (optee_test/ta/Makefile.gmake). This makes things simpler here and less fragile if something changes in optee_test. In addition, this should fix an "Argument list too long" error that can happen depending on the environment [1]. Finally, TAs can now be built in parallel (make -jN).
Link: https://github.com/OP-TEE/build/issues/744 [1]

optee_test_ext.mk: use the optee_test Makefile to build TAs

---

toolchain.mk

This is a ~~draft~~ PR ~~that attempts~~ to fix Issue #749 
Note that with this patch the build still fails when actually using the Rust toolchain. It seems to be a linker configuration issue. This is one of the error messages I'm getting:
```
Compiling optee-utee-sys v0.2.0 (/home/sean.linux/optee/out-br/build/optee_rust_examples_ext-1.0/optee-utee/optee-utee-sys)
error: linking with `/home/sean.linux/optee/build/../toolchains/aarch64/bin/aarch64-linux-ld.bfd` failed: exit status: 1
|
= note: LC_ALL="C" PATH="/home/sean.linux/optee/toolchains/rust/.rustup/toolchains/nightly-2023-12-18-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/sean.linux/optee/build/../toolchains/rust/.cargo/bin:/home/sean.linux/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/g …
```

Download Rust Toolchain during "make toolchains" on aarch64 hosts

---

qemu-check.exp
qemu.mk

Commit 71977485810c ("qemu_v8: Rework the QEMU arguments for run and check") has introduced QEMU_BASE_ARGS, QEMU_RUN_ARGS and QEMU_CHECK_ARGS in qemu_v8.mk. While doing so it inadvertently broke QEMU_VIRTFS_AUTOMOUNT=y / QEMU_VIRTFS_ENABLE=y / QEMU_PSS_ENABLE=y because those flags now add things to QEMU_RUN_ARGS rather than to QEMU_EXTRA_ARGS.
Therefore, change qemu.mk in a similar way to qemu_v8.mk and simplify a couple of things in qemu_check.exp.

qemu: align run and check on qemu_v8

---

qemu_v8.mk

Enable the QEMU max CPU for Xen. With this change simplify the configuration a little.

qemu_v8: enable max CPU for Xen

---

br-ext/board/stmicroelectronics/stm32mp1-tz/overlay-rootfs-rpmb/etc/init.d/S30optee

Retrieve the eMMC CID if only one eMMC device is found. We expect it to be used for OP-TEE RPMB secure storage. This change allows OS based on Linux kernel v6.2 or later to be more reliable on identifying the eMMC mmcblk device as since Linux kernel v6.2 the device index assigned by the kernel may change from one cold boot to another when they are several mmcblk devices on the platform, for example a plugged SD card and a soldered eMMC device.

stm32mp1: retrieve unique eMMC CID for tee-supplicant

---

clang/Dockerfile
toolchain.mk

Add a makefile target to download and build the Clang 18.1.7 sources and install the compiler into <PRJ_ROOT>/toolchains/clang-18.1.7/bin.
Usage example:
$ make clang-toolchains-build
$ PATH=$(pwd)/../toolchains/clang-18.1.7/bin:$PATH \
make -j$(nproc) COMPILER=clang check
The Clang build takes some significant time (about 12 minutes on my machine, a 24-core Intel Core i9-12900K) so may want to store a pre-built package somewhere in the future and have "make clang-toolchains" download that package. In the mean time, this new target allows to test OP-TEE with a recent LLVM toolchain.

toolchain.mk: add clang-toolchains-build to build Clang from sources

---

qemu_v8.mk

Change (UNAME_M) to (shell uname -m) to detect host, so that "RUST_ENABLE" can be correctly set on x86_64 hosts.

qemuv8: fix to enable Rust by default on x86_64 hosts only

---

rust.exp

Since optee_os commit b05636319287 ("Squashed commit upgrading to mbedtls-3.6.0"), the signature-verification-rs test takes a lot more time when CFG_CORE_DEBUG_CHECK_STACKS=y. Here are some values reported by "time signature-verification-rs" on QEMUv8:
[CFG_CORE_DEBUG_CHECK_STACKS=y]
Before: 0m 30s ; 0m 39s ; 0m 28s
After: 3m 8s ; 2m 13s ; 6m 36s ; 4m 14s
[CFG_CORE_DEBUG_CHECK_STACKS=n]
Before: 0m 1.55s ; 0m 1.57s ; 0m 1.77s 0m 0.87s
After: 0m 2.69s ; 0m 1.20s ; 0m 1.61s ; 0m 1.73s
Therefore, increase the timeout for this test specifically.

qemuv8: rust.exp: increase timeout of signature verification to 400s

---

fvp-psa-sp.mk

Should be merged together with or after the listed PR-s:
- https://github.com/OP-TEE/optee_os/pull/6945
- https://github.com/OP-TEE/optee_os/pull/6988

PAC/BTI enablement in TS

---

fvp-psa-sp.mk
trusted-services.mk

TS introduced a new shared library to help userspace applications integrate PSA clients. To avoid building this library multiple times add a dedicated build step, and share the resulting binary with all dependees.

fvp: Add libpsats support

---

qemu_v8.mk

Add CC="$(CCACHE)$(AARCH64_CROSS_COMPILE)gcc" to TF_A_EXPORTS for compiling TF-A v2.12.
Older and newer versions of TF-A can be compiled without issue if both CROSS_COMPILE and CC are set in TF_A_EXPORTS.
This dependency was introduced by the TF-A commit 3789c3c00090 ("build: determine toolchain tools dynamically")

qemu_v8: add CC=... to TF_A_EXPORTS

---

stm32mp1.mk

Building TF-A v2.11-rc0 and later fails when CROSS_COMPILE command includes space characters as when using ccache directives. This seems to be fixed by setting CC to the ccache and cross-toolchain directive.

stm32mp1: support build for TF-A v2.11 and later

---

qemu_v8.mk

When building on an aarch64 host, the following error occurs:
LD      /optee/trusted-firmware-a/build/qemu/release/bl31/bl31.elf
/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-buildroot-linux-gnu/14.1.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /optee/trusted-firmware-a/build/qemu/release/bl1/bl1.elf: error: PHDR segment not covered by LOAD segment
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1528: /optee/trusted-firmware-a/build/qemu/release/bl1/bl1.elf] Error 1
Setting LD and *not* setting CROSS_COMPILE fixes the problem. Tested on an aarch64 server running Ubuntu 24.04.

qemuv8: fix arm-tf link error on aarch64 build hosts

---

qemu_v8.mk

This reverts commit 9bf2bbe57184bb2c6ba73eacb2b11b7eeee40962. CI has become quite unstable since that commit was merged, see for instance the multiple failures in [1] and the absence of failure in [2]. I do not see any direct relationship betweem fTPM and the errors reported in the CI runs, but in order to make CI useful again we need to have it run reliably so disable MEASURED_BOOT_FTPM temporarily.
In my tests, 'make -j$(nproc) check-only XTEST_ARGS="-l 14"' always failed with a TA panic when MEASURED_BOOT_FTPM=y, and never when it is =n. The panic sometimes happens in xtest regression_4006, or sometimes in pkcs11_1021 or pkcs11_1023.
Link: [1] https://github.com/OP-TEE/optee_os/pull/7170
Link: [2] https://github.com/OP-TEE/optee_os/pull/7175

Revert "qemu_v8.mk: enable MEASURED_BOOT_FTPM by default"

---

qemu_v8.mk

By default, enable MEASURED_BOOT_FTPM. The previous issues when MEASURED_BOOT_FTPM was enabled has been resolved in [1].
Link: [1] https://github.com/OP-TEE/optee_os/pull/7177
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>

qemu_v8.mk: re-enable MEASURED_BOOT_FTPM by default

---

qemu_v8.mk

Add support for the new build path used for QEMU v9.2.0. The makefile will search first the new location and then the old location to maintain backward compatibility.

qemu_v8: support new path to QEMU v9.2.0

---

qemu.mk

The name of the QEMU v7 binary is qemu-system-arm not qemu-system-aarch64, so fix it.
Fixes: 329573518db6 ("qemu: support new path to QEMU v9.2.0")

qemu: fix path to QEMU

---

qemu-check.exp

Update the regular expression that catches RCU errors from the kernel in order to report an error upon:
[   79.434969] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
Without this fix, the test framework would either report a timeout (if the command causing the RCU message has hung), or report nothing (if the RCU message is triggered by a different thread of execution).

qemu-check.exp: catch more RCU messages

---

imx/u-boot_boot_script

The kernel has grown and overwrites fdt_addr when loaded. Fix this by updating the fdr_addr and initrd_addr variables the addresses further up in memory.

imx: update fdt_addr and initrd_addr

---

rpi3/firmware/uboot.env.txt

* Change kernel commandline to use TCP instead of UDP. Recent rpcbind defaults use TCP only (check with: 'rpcinfo -p <myip> | grep nfs'). Using TCP should give a more robust connections overall.
* Add "nfsversion" variable to ease experimentation with different NFS versions when using various systems.
* Update "nfsserverip" IP address to match examples in RPi3 documentation.
This relates to https://github.com/OP-TEE/optee_docs/pull/260.

rpi3: update uboot.env.txt defaults

---

qemu_v8.mk

Let common.mk set the default DEBUG value instead of setting a default value before including common.mk. The restores the default value 0 for DEBUG used before commit 85cc2db7efeb ("qemu_v8: add Trusted Services support"). This should also fix the CI build for Hafnium.
Fixes: 85cc2db7efeb ("qemu_v8: add Trusted Services support")

qemu_v8.mk: use DEBUG default value from common.mk

---

nanopc-t6.mk
nanopc-t6/nanopi6.h

Adds symbols to the overlay build and updates bootcmd to resize the DTB and apply the overlay.

nanopc-t6: update bootcmd to apply DTBO

---

versal/bootImage-versal-net-vnx-b2197-revA.bif
versal/fitImage-versal-net-vnx-b2197-revA.its
versal_net.mk

Based on Versal support.
Adds versal_net.mk and bootimage generation configuration
files.
Build commands:
$ make toolchains
$ make -j$(nproc)
$ make -j$(nproc) bootimage
The bootable image is versal/BOOT.BIN, usable with XSCT.

versal_net: add board support for AMD Versal Net

---

br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk

Invoke 'rust install toolchain' instead of relying on a side effect of 'cargo --version'. It looks like the side effect doesn't exist anymore. From optee_os CI:
2025-03-04T10:15:19.2947623Z Configuring OP-TEE rust examples
2025-03-04T10:15:19.3387454Z error: toolchain 'nightly-2023-12-18-x86_64-unknown-linux-gnu' is not installed
2025-03-04T10:15:19.3389280Z help: run `rustup toolchain install nightly-2023-12-18-x86_64-unknown-linux-gnu` to install it
2025-03-04T10:15:19.3403890Z make[2]: *** [package/pkg-generic.mk:273: /__w/optee_test/optee_repo_qemu_v8/out-br/build/optee_rust_examples_ext-1.0/.stamp_configured] Error 1
2025-03-04T10:15:19.3405144Z make[2]: *** Waiting for unfinished jobs....

optee_rust_examples_ext: use 'rust install toolchain'

---

qemu_v8.mk

Commit 1977c37e46d4 ("qemu_v8: support new path to QEMU v9.2.0") allows QEMU v9.2.0 to be used for 'make run[-only]', but it does not take into account 'make $(SCMI_DTB)'.

qemu_v8: fix "SCMI_DTB" with QEMU v9.2.0

---

kconfigs/u-boot_nanopc-t6.conf
nanopc-t6.mk
nanopc-t6/fit_wrapper.sh
nanopc-t6/rk3588-nanopi6-optee.dtso

Switch the NanoPC-T6 TEE load address from `0x08400000` to `0x30000000` by adding a local `fit_args.sh` and updating the device tree overlay. This aligns with [optee_os#7254](https://github.com/OP-TEE/optee_os/pull/7254), so merge this after that PR.

nanopc-t6: add fit_wrapper.sh with TEE_LOAD_ADDR=0x30000000

---

qemu.mk

Add CC="$(CCACHE)$(AARCH32_CROSS_COMPILE)gcc" to TF_A_EXPORTS for compiling TF-A v2.12.
Older and newer versions of TF-A can be compiled without issue if both CROSS_COMPILE and CC are set in TF_A_EXPORTS.
This dependency was introduced by the TF-A commit 3789c3c00090 ("build: determine toolchain tools dynamically")

qemu_v7: add CC=... to TF_A_EXPORTS

---

br-ext/package/ftpm_optee_ext/CMakeLists.txt
br-ext/package/linux_ftpm_mod_ext/CMakeLists.txt
br-ext/package/optee_os_ext/CMakeLists.txt

CMake 4.0 was released [1] which dropped compatibility with versions older than 3.5 and causes cmake_minimum_required(3.4) to fail. Bump the minimum required version to 3.5, which was released 9 years ago.
[1] https://www.kitware.com/cmake-4-0-0-available-for-download/
With v4.0.0 the following build error is observed:
|  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|  Compatibility with CMake < 3.5 has been removed from CMake.
|
|  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|  to tell CMake that the project requires at least <min> but has been updated
|  to work with policies introduced by <max> or earlier.
|
|  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
The issue was observed when building buildroot with OPTEE …

cmake: raise minimum required to 3.5

---

qemu-check.exp

Fix uninitialized variables in procedure 'check_test_result'.

qemu: Fix uninitialized variables

---

kconfigs/u-boot_qemu_v8.conf

A kernel built from v16-rc1 sources now overlaps with the default RAM disk load address in U-Boot 2025.07-rc1, causing a boot failure with a "Bad Data CRC" error.
Kernel end address:       0x45046A00
Previous RAM disk address:  0x45000000
This patch moves the RAM disk load address (`${ramdisk_addr_r}`) to `0x46000000`, resolving the memory conflict and providing a margin for future kernel growth.
The resulting boot error that is fixed was:
Image Name:   Linux kernel
Created:      2025-06-10  14:55:53 UTC
Image Type:   AArch64 Linux Kernel Image (uncompressed)
Data Size:    48523776 Bytes = 46.3 MiB
Load Address: 42200000
Entry Point:  42200000
Verifying Checksum ... Bad Data CRC
ERROR -22: can't get kernel image!

qemu_v8: u-boot: Relocate RAM disk to avoid kernel overlap
